package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ErrorMessage An error message received in an Azure Batch error response.
// swagger:model ErrorMessage
type ErrorMessage struct {

	// The language code of the error message
	Lang string `json:"lang,omitempty"`

	// The text of the message.
	Value string `json:"value,omitempty"`
}

// Validate validates this error message
func (m *ErrorMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
