package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLocationGetQuotasParams creates a new LocationGetQuotasParams object
// with the default values initialized.
func NewLocationGetQuotasParams() *LocationGetQuotasParams {
	var ()
	return &LocationGetQuotasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLocationGetQuotasParamsWithTimeout creates a new LocationGetQuotasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLocationGetQuotasParamsWithTimeout(timeout time.Duration) *LocationGetQuotasParams {
	var ()
	return &LocationGetQuotasParams{

		timeout: timeout,
	}
}

// NewLocationGetQuotasParamsWithContext creates a new LocationGetQuotasParams object
// with the default values initialized, and the ability to set a context for a request
func NewLocationGetQuotasParamsWithContext(ctx context.Context) *LocationGetQuotasParams {
	var ()
	return &LocationGetQuotasParams{

		Context: ctx,
	}
}

/*LocationGetQuotasParams contains all the parameters to send to the API endpoint
for the location get quotas operation typically these are written to a http.Request
*/
type LocationGetQuotasParams struct {

	/*APIVersion
	  The API version to be used with the HTTP request.

	*/
	APIVersion string
	/*LocationName
	  The desired region for the quotas.

	*/
	LocationName string
	/*SubscriptionID
	  A unique identifier of a Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the location get quotas params
func (o *LocationGetQuotasParams) WithTimeout(timeout time.Duration) *LocationGetQuotasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the location get quotas params
func (o *LocationGetQuotasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the location get quotas params
func (o *LocationGetQuotasParams) WithContext(ctx context.Context) *LocationGetQuotasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the location get quotas params
func (o *LocationGetQuotasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the location get quotas params
func (o *LocationGetQuotasParams) WithAPIVersion(aPIVersion string) *LocationGetQuotasParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the location get quotas params
func (o *LocationGetQuotasParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithLocationName adds the locationName to the location get quotas params
func (o *LocationGetQuotasParams) WithLocationName(locationName string) *LocationGetQuotasParams {
	o.SetLocationName(locationName)
	return o
}

// SetLocationName adds the locationName to the location get quotas params
func (o *LocationGetQuotasParams) SetLocationName(locationName string) {
	o.LocationName = locationName
}

// WithSubscriptionID adds the subscriptionID to the location get quotas params
func (o *LocationGetQuotasParams) WithSubscriptionID(subscriptionID string) *LocationGetQuotasParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the location get quotas params
func (o *LocationGetQuotasParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *LocationGetQuotasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param locationName
	if err := r.SetPathParam("locationName", o.LocationName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
