package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSnapshotsRevokeAccessParams creates a new SnapshotsRevokeAccessParams object
// with the default values initialized.
func NewSnapshotsRevokeAccessParams() *SnapshotsRevokeAccessParams {
	var ()
	return &SnapshotsRevokeAccessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSnapshotsRevokeAccessParamsWithTimeout creates a new SnapshotsRevokeAccessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSnapshotsRevokeAccessParamsWithTimeout(timeout time.Duration) *SnapshotsRevokeAccessParams {
	var ()
	return &SnapshotsRevokeAccessParams{

		timeout: timeout,
	}
}

// NewSnapshotsRevokeAccessParamsWithContext creates a new SnapshotsRevokeAccessParams object
// with the default values initialized, and the ability to set a context for a request
func NewSnapshotsRevokeAccessParamsWithContext(ctx context.Context) *SnapshotsRevokeAccessParams {
	var ()
	return &SnapshotsRevokeAccessParams{

		Context: ctx,
	}
}

/*SnapshotsRevokeAccessParams contains all the parameters to send to the API endpoint
for the snapshots revoke access operation typically these are written to a http.Request
*/
type SnapshotsRevokeAccessParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SnapshotName
	  The name of the snapshot within the given subscription and resource group.

	*/
	SnapshotName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithTimeout(timeout time.Duration) *SnapshotsRevokeAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithContext(ctx context.Context) *SnapshotsRevokeAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithAPIVersion(aPIVersion string) *SnapshotsRevokeAccessParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithResourceGroupName(resourceGroupName string) *SnapshotsRevokeAccessParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSnapshotName adds the snapshotName to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithSnapshotName(snapshotName string) *SnapshotsRevokeAccessParams {
	o.SetSnapshotName(snapshotName)
	return o
}

// SetSnapshotName adds the snapshotName to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetSnapshotName(snapshotName string) {
	o.SnapshotName = snapshotName
}

// WithSubscriptionID adds the subscriptionID to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) WithSubscriptionID(subscriptionID string) *SnapshotsRevokeAccessParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the snapshots revoke access params
func (o *SnapshotsRevokeAccessParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *SnapshotsRevokeAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param snapshotName
	if err := r.SetPathParam("snapshotName", o.SnapshotName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
