package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/disk/models"
)

// SnapshotsGrantAccessReader is a Reader for the SnapshotsGrantAccess structure.
type SnapshotsGrantAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SnapshotsGrantAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSnapshotsGrantAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewSnapshotsGrantAccessAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSnapshotsGrantAccessOK creates a SnapshotsGrantAccessOK with default headers values
func NewSnapshotsGrantAccessOK() *SnapshotsGrantAccessOK {
	return &SnapshotsGrantAccessOK{}
}

/*SnapshotsGrantAccessOK handles this case with default header values.

OK
*/
type SnapshotsGrantAccessOK struct {
	Payload *models.AccessURI
}

func (o *SnapshotsGrantAccessOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/snapshots/{snapshotName}/beginGetAccess][%d] snapshotsGrantAccessOK  %+v", 200, o.Payload)
}

func (o *SnapshotsGrantAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessURI)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotsGrantAccessAccepted creates a SnapshotsGrantAccessAccepted with default headers values
func NewSnapshotsGrantAccessAccepted() *SnapshotsGrantAccessAccepted {
	return &SnapshotsGrantAccessAccepted{}
}

/*SnapshotsGrantAccessAccepted handles this case with default header values.

Accepted
*/
type SnapshotsGrantAccessAccepted struct {
}

func (o *SnapshotsGrantAccessAccepted) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/snapshots/{snapshotName}/beginGetAccess][%d] snapshotsGrantAccessAccepted ", 202)
}

func (o *SnapshotsGrantAccessAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
