package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSnapshotsListByResourceGroupParams creates a new SnapshotsListByResourceGroupParams object
// with the default values initialized.
func NewSnapshotsListByResourceGroupParams() *SnapshotsListByResourceGroupParams {
	var ()
	return &SnapshotsListByResourceGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSnapshotsListByResourceGroupParamsWithTimeout creates a new SnapshotsListByResourceGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSnapshotsListByResourceGroupParamsWithTimeout(timeout time.Duration) *SnapshotsListByResourceGroupParams {
	var ()
	return &SnapshotsListByResourceGroupParams{

		timeout: timeout,
	}
}

// NewSnapshotsListByResourceGroupParamsWithContext creates a new SnapshotsListByResourceGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewSnapshotsListByResourceGroupParamsWithContext(ctx context.Context) *SnapshotsListByResourceGroupParams {
	var ()
	return &SnapshotsListByResourceGroupParams{

		Context: ctx,
	}
}

/*SnapshotsListByResourceGroupParams contains all the parameters to send to the API endpoint
for the snapshots list by resource group operation typically these are written to a http.Request
*/
type SnapshotsListByResourceGroupParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) WithTimeout(timeout time.Duration) *SnapshotsListByResourceGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) WithContext(ctx context.Context) *SnapshotsListByResourceGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) WithAPIVersion(aPIVersion string) *SnapshotsListByResourceGroupParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) WithResourceGroupName(resourceGroupName string) *SnapshotsListByResourceGroupParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) WithSubscriptionID(subscriptionID string) *SnapshotsListByResourceGroupParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the snapshots list by resource group params
func (o *SnapshotsListByResourceGroupParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *SnapshotsListByResourceGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
