package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSnapshotsGetParams creates a new SnapshotsGetParams object
// with the default values initialized.
func NewSnapshotsGetParams() *SnapshotsGetParams {
	var ()
	return &SnapshotsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSnapshotsGetParamsWithTimeout creates a new SnapshotsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSnapshotsGetParamsWithTimeout(timeout time.Duration) *SnapshotsGetParams {
	var ()
	return &SnapshotsGetParams{

		timeout: timeout,
	}
}

// NewSnapshotsGetParamsWithContext creates a new SnapshotsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSnapshotsGetParamsWithContext(ctx context.Context) *SnapshotsGetParams {
	var ()
	return &SnapshotsGetParams{

		Context: ctx,
	}
}

/*SnapshotsGetParams contains all the parameters to send to the API endpoint
for the snapshots get operation typically these are written to a http.Request
*/
type SnapshotsGetParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SnapshotName
	  The name of the snapshot within the given subscription and resource group.

	*/
	SnapshotName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the snapshots get params
func (o *SnapshotsGetParams) WithTimeout(timeout time.Duration) *SnapshotsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the snapshots get params
func (o *SnapshotsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the snapshots get params
func (o *SnapshotsGetParams) WithContext(ctx context.Context) *SnapshotsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the snapshots get params
func (o *SnapshotsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the snapshots get params
func (o *SnapshotsGetParams) WithAPIVersion(aPIVersion string) *SnapshotsGetParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the snapshots get params
func (o *SnapshotsGetParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the snapshots get params
func (o *SnapshotsGetParams) WithResourceGroupName(resourceGroupName string) *SnapshotsGetParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the snapshots get params
func (o *SnapshotsGetParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSnapshotName adds the snapshotName to the snapshots get params
func (o *SnapshotsGetParams) WithSnapshotName(snapshotName string) *SnapshotsGetParams {
	o.SetSnapshotName(snapshotName)
	return o
}

// SetSnapshotName adds the snapshotName to the snapshots get params
func (o *SnapshotsGetParams) SetSnapshotName(snapshotName string) {
	o.SnapshotName = snapshotName
}

// WithSubscriptionID adds the subscriptionID to the snapshots get params
func (o *SnapshotsGetParams) WithSubscriptionID(subscriptionID string) *SnapshotsGetParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the snapshots get params
func (o *SnapshotsGetParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *SnapshotsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param snapshotName
	if err := r.SetPathParam("snapshotName", o.SnapshotName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
