package virtual_machine_extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/compute/models"
)

// VirtualMachineExtensionsGetReader is a Reader for the VirtualMachineExtensionsGet structure.
type VirtualMachineExtensionsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualMachineExtensionsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualMachineExtensionsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualMachineExtensionsGetOK creates a VirtualMachineExtensionsGetOK with default headers values
func NewVirtualMachineExtensionsGetOK() *VirtualMachineExtensionsGetOK {
	return &VirtualMachineExtensionsGetOK{}
}

/*VirtualMachineExtensionsGetOK handles this case with default header values.

OK
*/
type VirtualMachineExtensionsGetOK struct {
	Payload *models.VirtualMachineExtension
}

func (o *VirtualMachineExtensionsGetOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/extensions/{vmExtensionName}][%d] virtualMachineExtensionsGetOK  %+v", 200, o.Payload)
}

func (o *VirtualMachineExtensionsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualMachineExtension)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
