package network_interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// NetworkInterfacesGetReader is a Reader for the NetworkInterfacesGet structure.
type NetworkInterfacesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkInterfacesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetworkInterfacesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNetworkInterfacesGetOK creates a NetworkInterfacesGetOK with default headers values
func NewNetworkInterfacesGetOK() *NetworkInterfacesGetOK {
	return &NetworkInterfacesGetOK{}
}

/*NetworkInterfacesGetOK handles this case with default header values.

NetworkInterfacesGetOK network interfaces get o k
*/
type NetworkInterfacesGetOK struct {
	Payload *models.NetworkInterface
}

func (o *NetworkInterfacesGetOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkInterfaces/{networkInterfaceName}][%d] networkInterfacesGetOK  %+v", 200, o.Payload)
}

func (o *NetworkInterfacesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkInterface)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
