package network_interfaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams creates a new NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams object
// with the default values initialized.
func NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams() *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	var ()
	return &NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParamsWithTimeout creates a new NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParamsWithTimeout(timeout time.Duration) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	var ()
	return &NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams{

		timeout: timeout,
	}
}

// NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParamsWithContext creates a new NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParamsWithContext(ctx context.Context) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	var ()
	return &NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams{

		Context: ctx,
	}
}

/*NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams contains all the parameters to send to the API endpoint
for the network interfaces list virtual machine scale set network interfaces operation typically these are written to a http.Request
*/
type NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string
	/*VirtualMachineScaleSetName
	  The name of the virtual machine scale set.

	*/
	VirtualMachineScaleSetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithTimeout(timeout time.Duration) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithContext(ctx context.Context) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithAPIVersion(aPIVersion string) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithResourceGroupName(resourceGroupName string) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithSubscriptionID(subscriptionID string) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WithVirtualMachineScaleSetName adds the virtualMachineScaleSetName to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WithVirtualMachineScaleSetName(virtualMachineScaleSetName string) *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams {
	o.SetVirtualMachineScaleSetName(virtualMachineScaleSetName)
	return o
}

// SetVirtualMachineScaleSetName adds the virtualMachineScaleSetName to the network interfaces list virtual machine scale set network interfaces params
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) SetVirtualMachineScaleSetName(virtualMachineScaleSetName string) {
	o.VirtualMachineScaleSetName = virtualMachineScaleSetName
}

// WriteToRequest writes these params to a swagger request
func (o *NetworkInterfacesListVirtualMachineScaleSetNetworkInterfacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	// path param virtualMachineScaleSetName
	if err := r.SetPathParam("virtualMachineScaleSetName", o.VirtualMachineScaleSetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
