package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batch/models"
)

// NewPoolEvaluateAutoScaleParams creates a new PoolEvaluateAutoScaleParams object
// with the default values initialized.
func NewPoolEvaluateAutoScaleParams() *PoolEvaluateAutoScaleParams {
	var (
		returnClientRequestIDDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &PoolEvaluateAutoScaleParams{
		ReturnClientRequestID: &returnClientRequestIDDefault,
		Timeout:               &timeoutDefault,

		requestTimeout: cr.DefaultTimeout,
	}
}

// NewPoolEvaluateAutoScaleParamsWithTimeout creates a new PoolEvaluateAutoScaleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPoolEvaluateAutoScaleParamsWithTimeout(timeout time.Duration) *PoolEvaluateAutoScaleParams {
	var (
		returnClientRequestIDDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &PoolEvaluateAutoScaleParams{
		ReturnClientRequestID: &returnClientRequestIDDefault,
		Timeout:               &timeoutDefault,

		requestTimeout: timeout,
	}
}

// NewPoolEvaluateAutoScaleParamsWithContext creates a new PoolEvaluateAutoScaleParams object
// with the default values initialized, and the ability to set a context for a request
func NewPoolEvaluateAutoScaleParamsWithContext(ctx context.Context) *PoolEvaluateAutoScaleParams {
	var (
		returnClientRequestIdDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &PoolEvaluateAutoScaleParams{
		ReturnClientRequestID: &returnClientRequestIdDefault,
		Timeout:               &timeoutDefault,

		Context: ctx,
	}
}

/*PoolEvaluateAutoScaleParams contains all the parameters to send to the API endpoint
for the pool evaluate auto scale operation typically these are written to a http.Request
*/
type PoolEvaluateAutoScaleParams struct {

	/*APIVersion
	  Client API Version.

	*/
	APIVersion string
	/*ClientRequestID
	  The caller-generated request identity, in the form of a GUID with no decoration such as curly braces, e.g. 9C4D50EE-2D56-4CD3-8152-34347DC9F2B0.

	*/
	ClientRequestID *string
	/*OcpDate
	  The time the request was issued. If not specified, this header will be automatically populated with the current system clock time.

	*/
	OcpDate *string
	/*PoolEvaluateAutoScaleParameter
	  The parameters for the request.

	*/
	PoolEvaluateAutoScaleParameter *models.PoolEvaluateAutoScaleParameter
	/*PoolID
	  The ID of the pool on which to evaluate the automatic scaling formula.

	*/
	PoolID string
	/*ReturnClientRequestID
	  Whether the server should return the client-request-id in the response.

	*/
	ReturnClientRequestID *bool
	/*Timeout
	  The maximum time that the server can spend processing the request, in seconds. The default is 30 seconds.

	*/
	Timeout *int32

	requestTimeout time.Duration
	Context        context.Context
	HTTPClient     *http.Client
}

// WithRequestTimeout adds the timeout to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithRequestTimeout(timeout time.Duration) *PoolEvaluateAutoScaleParams {
	o.SetRequestTimeout(timeout)
	return o
}

// SetRequestTimeout adds the timeout to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetRequestTimeout(timeout time.Duration) {
	o.requestTimeout = timeout
}

// WithContext adds the context to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithContext(ctx context.Context) *PoolEvaluateAutoScaleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithAPIVersion(aPIVersion string) *PoolEvaluateAutoScaleParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithClientRequestID adds the clientRequestID to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithClientRequestID(clientRequestID *string) *PoolEvaluateAutoScaleParams {
	o.SetClientRequestID(clientRequestID)
	return o
}

// SetClientRequestID adds the clientRequestId to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetClientRequestID(clientRequestID *string) {
	o.ClientRequestID = clientRequestID
}

// WithOcpDate adds the ocpDate to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithOcpDate(ocpDate *string) *PoolEvaluateAutoScaleParams {
	o.SetOcpDate(ocpDate)
	return o
}

// SetOcpDate adds the ocpDate to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetOcpDate(ocpDate *string) {
	o.OcpDate = ocpDate
}

// WithPoolEvaluateAutoScaleParameter adds the poolEvaluateAutoScaleParameter to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithPoolEvaluateAutoScaleParameter(poolEvaluateAutoScaleParameter *models.PoolEvaluateAutoScaleParameter) *PoolEvaluateAutoScaleParams {
	o.SetPoolEvaluateAutoScaleParameter(poolEvaluateAutoScaleParameter)
	return o
}

// SetPoolEvaluateAutoScaleParameter adds the poolEvaluateAutoScaleParameter to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetPoolEvaluateAutoScaleParameter(poolEvaluateAutoScaleParameter *models.PoolEvaluateAutoScaleParameter) {
	o.PoolEvaluateAutoScaleParameter = poolEvaluateAutoScaleParameter
}

// WithPoolID adds the poolID to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithPoolID(poolID string) *PoolEvaluateAutoScaleParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetPoolID(poolID string) {
	o.PoolID = poolID
}

// WithReturnClientRequestID adds the returnClientRequestID to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithReturnClientRequestID(returnClientRequestID *bool) *PoolEvaluateAutoScaleParams {
	o.SetReturnClientRequestID(returnClientRequestID)
	return o
}

// SetReturnClientRequestID adds the returnClientRequestId to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetReturnClientRequestID(returnClientRequestID *bool) {
	o.ReturnClientRequestID = returnClientRequestID
}

// WithTimeout adds the timeout to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) WithTimeout(timeout *int32) *PoolEvaluateAutoScaleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pool evaluate auto scale params
func (o *PoolEvaluateAutoScaleParams) SetTimeout(timeout *int32) {
	o.Timeout = timeout
}

// WriteToRequest writes these params to a swagger request
func (o *PoolEvaluateAutoScaleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.requestTimeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.ClientRequestID != nil {

		// header param client-request-id
		if err := r.SetHeaderParam("client-request-id", *o.ClientRequestID); err != nil {
			return err
		}

	}

	if o.OcpDate != nil {

		// header param ocp-date
		if err := r.SetHeaderParam("ocp-date", *o.OcpDate); err != nil {
			return err
		}

	}

	if o.PoolEvaluateAutoScaleParameter == nil {
		o.PoolEvaluateAutoScaleParameter = new(models.PoolEvaluateAutoScaleParameter)
	}

	if err := r.SetBodyParam(o.PoolEvaluateAutoScaleParameter); err != nil {
		return err
	}

	// path param poolId
	if err := r.SetPathParam("poolId", o.PoolID); err != nil {
		return err
	}

	if o.ReturnClientRequestID != nil {

		// header param return-client-request-id
		if err := r.SetHeaderParam("return-client-request-id", swag.FormatBool(*o.ReturnClientRequestID)); err != nil {
			return err
		}

	}

	if o.Timeout != nil {

		// query param timeout
		var qrTimeout int32
		if o.Timeout != nil {
			qrTimeout = *o.Timeout
		}
		qTimeout := swag.FormatInt32(qrTimeout)
		if qTimeout != "" {
			if err := r.SetQueryParam("timeout", qTimeout); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
