package load_balancers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadBalancersGetParams creates a new LoadBalancersGetParams object
// with the default values initialized.
func NewLoadBalancersGetParams() *LoadBalancersGetParams {
	var ()
	return &LoadBalancersGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadBalancersGetParamsWithTimeout creates a new LoadBalancersGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadBalancersGetParamsWithTimeout(timeout time.Duration) *LoadBalancersGetParams {
	var ()
	return &LoadBalancersGetParams{

		timeout: timeout,
	}
}

// NewLoadBalancersGetParamsWithContext creates a new LoadBalancersGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadBalancersGetParamsWithContext(ctx context.Context) *LoadBalancersGetParams {
	var ()
	return &LoadBalancersGetParams{

		Context: ctx,
	}
}

/*LoadBalancersGetParams contains all the parameters to send to the API endpoint
for the load balancers get operation typically these are written to a http.Request
*/
type LoadBalancersGetParams struct {

	/*NrDollarExpand
	  expand references resources.

	*/
	DollarExpand *string
	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*LoadBalancerName
	  The name of the loadBalancer.

	*/
	LoadBalancerName string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load balancers get params
func (o *LoadBalancersGetParams) WithTimeout(timeout time.Duration) *LoadBalancersGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load balancers get params
func (o *LoadBalancersGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load balancers get params
func (o *LoadBalancersGetParams) WithContext(ctx context.Context) *LoadBalancersGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load balancers get params
func (o *LoadBalancersGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithDollarExpand adds the dollarExpand to the load balancers get params
func (o *LoadBalancersGetParams) WithDollarExpand(dollarExpand *string) *LoadBalancersGetParams {
	o.SetDollarExpand(dollarExpand)
	return o
}

// SetDollarExpand adds the dollarExpand to the load balancers get params
func (o *LoadBalancersGetParams) SetDollarExpand(dollarExpand *string) {
	o.DollarExpand = dollarExpand
}

// WithAPIVersion adds the aPIVersion to the load balancers get params
func (o *LoadBalancersGetParams) WithAPIVersion(aPIVersion string) *LoadBalancersGetParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the load balancers get params
func (o *LoadBalancersGetParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithLoadBalancerName adds the loadBalancerName to the load balancers get params
func (o *LoadBalancersGetParams) WithLoadBalancerName(loadBalancerName string) *LoadBalancersGetParams {
	o.SetLoadBalancerName(loadBalancerName)
	return o
}

// SetLoadBalancerName adds the loadBalancerName to the load balancers get params
func (o *LoadBalancersGetParams) SetLoadBalancerName(loadBalancerName string) {
	o.LoadBalancerName = loadBalancerName
}

// WithResourceGroupName adds the resourceGroupName to the load balancers get params
func (o *LoadBalancersGetParams) WithResourceGroupName(resourceGroupName string) *LoadBalancersGetParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the load balancers get params
func (o *LoadBalancersGetParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the load balancers get params
func (o *LoadBalancersGetParams) WithSubscriptionID(subscriptionID string) *LoadBalancersGetParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the load balancers get params
func (o *LoadBalancersGetParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *LoadBalancersGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.DollarExpand != nil {

		// query param $expand
		var qrNrDollarExpand string
		if o.DollarExpand != nil {
			qrNrDollarExpand = *o.DollarExpand
		}
		qNrDollarExpand := qrNrDollarExpand
		if qNrDollarExpand != "" {
			if err := r.SetQueryParam("$expand", qNrDollarExpand); err != nil {
				return err
			}
		}

	}

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param loadBalancerName
	if err := r.SetPathParam("loadBalancerName", o.LoadBalancerName); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
