package virtual_network_gateway_connections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// VirtualNetworkGatewayConnectionsListReader is a Reader for the VirtualNetworkGatewayConnectionsList structure.
type VirtualNetworkGatewayConnectionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualNetworkGatewayConnectionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualNetworkGatewayConnectionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualNetworkGatewayConnectionsListOK creates a VirtualNetworkGatewayConnectionsListOK with default headers values
func NewVirtualNetworkGatewayConnectionsListOK() *VirtualNetworkGatewayConnectionsListOK {
	return &VirtualNetworkGatewayConnectionsListOK{}
}

/*VirtualNetworkGatewayConnectionsListOK handles this case with default header values.

VirtualNetworkGatewayConnectionsListOK virtual network gateway connections list o k
*/
type VirtualNetworkGatewayConnectionsListOK struct {
	Payload *models.VirtualNetworkGatewayConnectionListResult
}

func (o *VirtualNetworkGatewayConnectionsListOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/connections][%d] virtualNetworkGatewayConnectionsListOK  %+v", 200, o.Payload)
}

func (o *VirtualNetworkGatewayConnectionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualNetworkGatewayConnectionListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
