package usages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUsagesListParams creates a new UsagesListParams object
// with the default values initialized.
func NewUsagesListParams() *UsagesListParams {
	var ()
	return &UsagesListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUsagesListParamsWithTimeout creates a new UsagesListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUsagesListParamsWithTimeout(timeout time.Duration) *UsagesListParams {
	var ()
	return &UsagesListParams{

		timeout: timeout,
	}
}

// NewUsagesListParamsWithContext creates a new UsagesListParams object
// with the default values initialized, and the ability to set a context for a request
func NewUsagesListParamsWithContext(ctx context.Context) *UsagesListParams {
	var ()
	return &UsagesListParams{

		Context: ctx,
	}
}

/*UsagesListParams contains all the parameters to send to the API endpoint
for the usages list operation typically these are written to a http.Request
*/
type UsagesListParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*Location
	  The location upon which resource usage is queried.

	*/
	Location string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the usages list params
func (o *UsagesListParams) WithTimeout(timeout time.Duration) *UsagesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the usages list params
func (o *UsagesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the usages list params
func (o *UsagesListParams) WithContext(ctx context.Context) *UsagesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the usages list params
func (o *UsagesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the usages list params
func (o *UsagesListParams) WithAPIVersion(aPIVersion string) *UsagesListParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the usages list params
func (o *UsagesListParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithLocation adds the location to the usages list params
func (o *UsagesListParams) WithLocation(location string) *UsagesListParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the usages list params
func (o *UsagesListParams) SetLocation(location string) {
	o.Location = location
}

// WithSubscriptionID adds the subscriptionID to the usages list params
func (o *UsagesListParams) WithSubscriptionID(subscriptionID string) *UsagesListParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the usages list params
func (o *UsagesListParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *UsagesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param location
	if err := r.SetPathParam("location", o.Location); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
