package route_tables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// RouteTablesListAllReader is a Reader for the RouteTablesListAll structure.
type RouteTablesListAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteTablesListAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRouteTablesListAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRouteTablesListAllOK creates a RouteTablesListAllOK with default headers values
func NewRouteTablesListAllOK() *RouteTablesListAllOK {
	return &RouteTablesListAllOK{}
}

/*RouteTablesListAllOK handles this case with default header values.

RouteTablesListAllOK route tables list all o k
*/
type RouteTablesListAllOK struct {
	Payload *models.RouteTableListResult
}

func (o *RouteTablesListAllOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/providers/Microsoft.Network/routeTables][%d] routeTablesListAllOK  %+v", 200, o.Payload)
}

func (o *RouteTablesListAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RouteTableListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
