package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/resource/models"
)

// ProvidersRegisterReader is a Reader for the ProvidersRegister structure.
type ProvidersRegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProvidersRegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProvidersRegisterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProvidersRegisterOK creates a ProvidersRegisterOK with default headers values
func NewProvidersRegisterOK() *ProvidersRegisterOK {
	return &ProvidersRegisterOK{}
}

/*ProvidersRegisterOK handles this case with default header values.

OK - Returns information about the resource provider.
*/
type ProvidersRegisterOK struct {
	Payload *models.Provider
}

func (o *ProvidersRegisterOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/providers/{resourceProviderNamespace}/register][%d] providersRegisterOK  %+v", 200, o.Payload)
}

func (o *ProvidersRegisterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Provider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
