package resource_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/resource/models"
)

// ResourceGroupsListResourcesReader is a Reader for the ResourceGroupsListResources structure.
type ResourceGroupsListResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResourceGroupsListResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewResourceGroupsListResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResourceGroupsListResourcesOK creates a ResourceGroupsListResourcesOK with default headers values
func NewResourceGroupsListResourcesOK() *ResourceGroupsListResourcesOK {
	return &ResourceGroupsListResourcesOK{}
}

/*ResourceGroupsListResourcesOK handles this case with default header values.

OK - Returns an array of resources
*/
type ResourceGroupsListResourcesOK struct {
	Payload *models.ResourceListResult
}

func (o *ResourceGroupsListResourcesOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/resources][%d] resourceGroupsListResourcesOK  %+v", 200, o.Payload)
}

func (o *ResourceGroupsListResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
