package resource_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/resource/models"
)

// ResourceGroupsPatchReader is a Reader for the ResourceGroupsPatch structure.
type ResourceGroupsPatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResourceGroupsPatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewResourceGroupsPatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResourceGroupsPatchOK creates a ResourceGroupsPatchOK with default headers values
func NewResourceGroupsPatchOK() *ResourceGroupsPatchOK {
	return &ResourceGroupsPatchOK{}
}

/*ResourceGroupsPatchOK handles this case with default header values.

OK - Returns information about the resource group.
*/
type ResourceGroupsPatchOK struct {
	Payload *models.ResourceGroup
}

func (o *ResourceGroupsPatchOK) Error() string {
	return fmt.Sprintf("[PATCH /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}][%d] resourceGroupsPatchOK  %+v", 200, o.Payload)
}

func (o *ResourceGroupsPatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
