package express_route_circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewExpressRouteCircuitsGetParams creates a new ExpressRouteCircuitsGetParams object
// with the default values initialized.
func NewExpressRouteCircuitsGetParams() *ExpressRouteCircuitsGetParams {
	var ()
	return &ExpressRouteCircuitsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExpressRouteCircuitsGetParamsWithTimeout creates a new ExpressRouteCircuitsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExpressRouteCircuitsGetParamsWithTimeout(timeout time.Duration) *ExpressRouteCircuitsGetParams {
	var ()
	return &ExpressRouteCircuitsGetParams{

		timeout: timeout,
	}
}

// NewExpressRouteCircuitsGetParamsWithContext creates a new ExpressRouteCircuitsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewExpressRouteCircuitsGetParamsWithContext(ctx context.Context) *ExpressRouteCircuitsGetParams {
	var ()
	return &ExpressRouteCircuitsGetParams{

		Context: ctx,
	}
}

/*ExpressRouteCircuitsGetParams contains all the parameters to send to the API endpoint
for the express route circuits get operation typically these are written to a http.Request
*/
type ExpressRouteCircuitsGetParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*CircuitName
	  The name of the circuit.

	*/
	CircuitName string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithTimeout(timeout time.Duration) *ExpressRouteCircuitsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithContext(ctx context.Context) *ExpressRouteCircuitsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithAPIVersion(aPIVersion string) *ExpressRouteCircuitsGetParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithCircuitName adds the circuitName to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithCircuitName(circuitName string) *ExpressRouteCircuitsGetParams {
	o.SetCircuitName(circuitName)
	return o
}

// SetCircuitName adds the circuitName to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetCircuitName(circuitName string) {
	o.CircuitName = circuitName
}

// WithResourceGroupName adds the resourceGroupName to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithResourceGroupName(resourceGroupName string) *ExpressRouteCircuitsGetParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) WithSubscriptionID(subscriptionID string) *ExpressRouteCircuitsGetParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the express route circuits get params
func (o *ExpressRouteCircuitsGetParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *ExpressRouteCircuitsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param circuitName
	if err := r.SetPathParam("circuitName", o.CircuitName); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
