package disks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/disk/models"
)

// DisksRevokeAccessReader is a Reader for the DisksRevokeAccess structure.
type DisksRevokeAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisksRevokeAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDisksRevokeAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewDisksRevokeAccessAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDisksRevokeAccessOK creates a DisksRevokeAccessOK with default headers values
func NewDisksRevokeAccessOK() *DisksRevokeAccessOK {
	return &DisksRevokeAccessOK{}
}

/*DisksRevokeAccessOK handles this case with default header values.

OK
*/
type DisksRevokeAccessOK struct {
	Payload *models.OperationStatusResponse
}

func (o *DisksRevokeAccessOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/disks/{diskName}/endGetAccess][%d] disksRevokeAccessOK  %+v", 200, o.Payload)
}

func (o *DisksRevokeAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisksRevokeAccessAccepted creates a DisksRevokeAccessAccepted with default headers values
func NewDisksRevokeAccessAccepted() *DisksRevokeAccessAccepted {
	return &DisksRevokeAccessAccepted{}
}

/*DisksRevokeAccessAccepted handles this case with default header values.

Accepted
*/
type DisksRevokeAccessAccepted struct {
}

func (o *DisksRevokeAccessAccepted) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/disks/{diskName}/endGetAccess][%d] disksRevokeAccessAccepted ", 202)
}

func (o *DisksRevokeAccessAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
