package disks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/disk/models"
)

// NewDisksGrantAccessParams creates a new DisksGrantAccessParams object
// with the default values initialized.
func NewDisksGrantAccessParams() *DisksGrantAccessParams {
	var ()
	return &DisksGrantAccessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisksGrantAccessParamsWithTimeout creates a new DisksGrantAccessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisksGrantAccessParamsWithTimeout(timeout time.Duration) *DisksGrantAccessParams {
	var ()
	return &DisksGrantAccessParams{

		timeout: timeout,
	}
}

// NewDisksGrantAccessParamsWithContext creates a new DisksGrantAccessParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisksGrantAccessParamsWithContext(ctx context.Context) *DisksGrantAccessParams {
	var ()
	return &DisksGrantAccessParams{

		Context: ctx,
	}
}

/*DisksGrantAccessParams contains all the parameters to send to the API endpoint
for the disks grant access operation typically these are written to a http.Request
*/
type DisksGrantAccessParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*DiskName
	  The name of the disk within the given subscription and resource group.

	*/
	DiskName string
	/*GrantAccessData
	  Access data object supplied in the body of the get disk access operation.

	*/
	GrantAccessData *models.GrantAccessData
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disks grant access params
func (o *DisksGrantAccessParams) WithTimeout(timeout time.Duration) *DisksGrantAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disks grant access params
func (o *DisksGrantAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disks grant access params
func (o *DisksGrantAccessParams) WithContext(ctx context.Context) *DisksGrantAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disks grant access params
func (o *DisksGrantAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the disks grant access params
func (o *DisksGrantAccessParams) WithAPIVersion(aPIVersion string) *DisksGrantAccessParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the disks grant access params
func (o *DisksGrantAccessParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithDiskName adds the diskName to the disks grant access params
func (o *DisksGrantAccessParams) WithDiskName(diskName string) *DisksGrantAccessParams {
	o.SetDiskName(diskName)
	return o
}

// SetDiskName adds the diskName to the disks grant access params
func (o *DisksGrantAccessParams) SetDiskName(diskName string) {
	o.DiskName = diskName
}

// WithGrantAccessData adds the grantAccessData to the disks grant access params
func (o *DisksGrantAccessParams) WithGrantAccessData(grantAccessData *models.GrantAccessData) *DisksGrantAccessParams {
	o.SetGrantAccessData(grantAccessData)
	return o
}

// SetGrantAccessData adds the grantAccessData to the disks grant access params
func (o *DisksGrantAccessParams) SetGrantAccessData(grantAccessData *models.GrantAccessData) {
	o.GrantAccessData = grantAccessData
}

// WithResourceGroupName adds the resourceGroupName to the disks grant access params
func (o *DisksGrantAccessParams) WithResourceGroupName(resourceGroupName string) *DisksGrantAccessParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the disks grant access params
func (o *DisksGrantAccessParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the disks grant access params
func (o *DisksGrantAccessParams) WithSubscriptionID(subscriptionID string) *DisksGrantAccessParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the disks grant access params
func (o *DisksGrantAccessParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *DisksGrantAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param diskName
	if err := r.SetPathParam("diskName", o.DiskName); err != nil {
		return err
	}

	if o.GrantAccessData == nil {
		o.GrantAccessData = new(models.GrantAccessData)
	}

	if err := r.SetBodyParam(o.GrantAccessData); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
