package disks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDisksDeleteParams creates a new DisksDeleteParams object
// with the default values initialized.
func NewDisksDeleteParams() *DisksDeleteParams {
	var ()
	return &DisksDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDisksDeleteParamsWithTimeout creates a new DisksDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDisksDeleteParamsWithTimeout(timeout time.Duration) *DisksDeleteParams {
	var ()
	return &DisksDeleteParams{

		timeout: timeout,
	}
}

// NewDisksDeleteParamsWithContext creates a new DisksDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDisksDeleteParamsWithContext(ctx context.Context) *DisksDeleteParams {
	var ()
	return &DisksDeleteParams{

		Context: ctx,
	}
}

/*DisksDeleteParams contains all the parameters to send to the API endpoint
for the disks delete operation typically these are written to a http.Request
*/
type DisksDeleteParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*DiskName
	  The name of the disk within the given subscription and resource group.

	*/
	DiskName string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the disks delete params
func (o *DisksDeleteParams) WithTimeout(timeout time.Duration) *DisksDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the disks delete params
func (o *DisksDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the disks delete params
func (o *DisksDeleteParams) WithContext(ctx context.Context) *DisksDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the disks delete params
func (o *DisksDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the disks delete params
func (o *DisksDeleteParams) WithAPIVersion(aPIVersion string) *DisksDeleteParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the disks delete params
func (o *DisksDeleteParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithDiskName adds the diskName to the disks delete params
func (o *DisksDeleteParams) WithDiskName(diskName string) *DisksDeleteParams {
	o.SetDiskName(diskName)
	return o
}

// SetDiskName adds the diskName to the disks delete params
func (o *DisksDeleteParams) SetDiskName(diskName string) {
	o.DiskName = diskName
}

// WithResourceGroupName adds the resourceGroupName to the disks delete params
func (o *DisksDeleteParams) WithResourceGroupName(resourceGroupName string) *DisksDeleteParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the disks delete params
func (o *DisksDeleteParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the disks delete params
func (o *DisksDeleteParams) WithSubscriptionID(subscriptionID string) *DisksDeleteParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the disks delete params
func (o *DisksDeleteParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *DisksDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param diskName
	if err := r.SetPathParam("diskName", o.DiskName); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
