package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/resource/models"
)

// DeploymentsGetReader is a Reader for the DeploymentsGet structure.
type DeploymentsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeploymentsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeploymentsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeploymentsGetOK creates a DeploymentsGetOK with default headers values
func NewDeploymentsGetOK() *DeploymentsGetOK {
	return &DeploymentsGetOK{}
}

/*DeploymentsGetOK handles this case with default header values.

OK - Returns information about the deployment, including provisioning status.
*/
type DeploymentsGetOK struct {
	Payload *models.DeploymentExtended
}

func (o *DeploymentsGetOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Resources/deployments/{deploymentName}][%d] deploymentsGetOK  %+v", 200, o.Payload)
}

func (o *DeploymentsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeploymentExtended)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
