package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RoutesDeleteReader is a Reader for the RoutesDelete structure.
type RoutesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RoutesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRoutesDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewRoutesDeleteAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewRoutesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRoutesDeleteOK creates a RoutesDeleteOK with default headers values
func NewRoutesDeleteOK() *RoutesDeleteOK {
	return &RoutesDeleteOK{}
}

/*RoutesDeleteOK handles this case with default header values.

RoutesDeleteOK routes delete o k
*/
type RoutesDeleteOK struct {
}

func (o *RoutesDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/routeTables/{routeTableName}/routes/{routeName}][%d] routesDeleteOK ", 200)
}

func (o *RoutesDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRoutesDeleteAccepted creates a RoutesDeleteAccepted with default headers values
func NewRoutesDeleteAccepted() *RoutesDeleteAccepted {
	return &RoutesDeleteAccepted{}
}

/*RoutesDeleteAccepted handles this case with default header values.

RoutesDeleteAccepted routes delete accepted
*/
type RoutesDeleteAccepted struct {
}

func (o *RoutesDeleteAccepted) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/routeTables/{routeTableName}/routes/{routeName}][%d] routesDeleteAccepted ", 202)
}

func (o *RoutesDeleteAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRoutesDeleteNoContent creates a RoutesDeleteNoContent with default headers values
func NewRoutesDeleteNoContent() *RoutesDeleteNoContent {
	return &RoutesDeleteNoContent{}
}

/*RoutesDeleteNoContent handles this case with default header values.

RoutesDeleteNoContent routes delete no content
*/
type RoutesDeleteNoContent struct {
}

func (o *RoutesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/routeTables/{routeTableName}/routes/{routeName}][%d] routesDeleteNoContent ", 204)
}

func (o *RoutesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
