package virtual_machine_extension_images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVirtualMachineExtensionImagesListTypesParams creates a new VirtualMachineExtensionImagesListTypesParams object
// with the default values initialized.
func NewVirtualMachineExtensionImagesListTypesParams() *VirtualMachineExtensionImagesListTypesParams {
	var ()
	return &VirtualMachineExtensionImagesListTypesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualMachineExtensionImagesListTypesParamsWithTimeout creates a new VirtualMachineExtensionImagesListTypesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVirtualMachineExtensionImagesListTypesParamsWithTimeout(timeout time.Duration) *VirtualMachineExtensionImagesListTypesParams {
	var ()
	return &VirtualMachineExtensionImagesListTypesParams{

		timeout: timeout,
	}
}

// NewVirtualMachineExtensionImagesListTypesParamsWithContext creates a new VirtualMachineExtensionImagesListTypesParams object
// with the default values initialized, and the ability to set a context for a request
func NewVirtualMachineExtensionImagesListTypesParamsWithContext(ctx context.Context) *VirtualMachineExtensionImagesListTypesParams {
	var ()
	return &VirtualMachineExtensionImagesListTypesParams{

		Context: ctx,
	}
}

/*VirtualMachineExtensionImagesListTypesParams contains all the parameters to send to the API endpoint
for the virtual machine extension images list types operation typically these are written to a http.Request
*/
type VirtualMachineExtensionImagesListTypesParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*Location*/
	Location string
	/*PublisherName*/
	PublisherName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithTimeout(timeout time.Duration) *VirtualMachineExtensionImagesListTypesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithContext(ctx context.Context) *VirtualMachineExtensionImagesListTypesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithAPIVersion(aPIVersion string) *VirtualMachineExtensionImagesListTypesParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithLocation adds the location to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithLocation(location string) *VirtualMachineExtensionImagesListTypesParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetLocation(location string) {
	o.Location = location
}

// WithPublisherName adds the publisherName to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithPublisherName(publisherName string) *VirtualMachineExtensionImagesListTypesParams {
	o.SetPublisherName(publisherName)
	return o
}

// SetPublisherName adds the publisherName to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetPublisherName(publisherName string) {
	o.PublisherName = publisherName
}

// WithSubscriptionID adds the subscriptionID to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) WithSubscriptionID(subscriptionID string) *VirtualMachineExtensionImagesListTypesParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the virtual machine extension images list types params
func (o *VirtualMachineExtensionImagesListTypesParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualMachineExtensionImagesListTypesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param location
	if err := r.SetPathParam("location", o.Location); err != nil {
		return err
	}

	// path param publisherName
	if err := r.SetPathParam("publisherName", o.PublisherName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
