package virtual_machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVirtualMachinesGeneralizeParams creates a new VirtualMachinesGeneralizeParams object
// with the default values initialized.
func NewVirtualMachinesGeneralizeParams() *VirtualMachinesGeneralizeParams {
	var ()
	return &VirtualMachinesGeneralizeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualMachinesGeneralizeParamsWithTimeout creates a new VirtualMachinesGeneralizeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVirtualMachinesGeneralizeParamsWithTimeout(timeout time.Duration) *VirtualMachinesGeneralizeParams {
	var ()
	return &VirtualMachinesGeneralizeParams{

		timeout: timeout,
	}
}

// NewVirtualMachinesGeneralizeParamsWithContext creates a new VirtualMachinesGeneralizeParams object
// with the default values initialized, and the ability to set a context for a request
func NewVirtualMachinesGeneralizeParamsWithContext(ctx context.Context) *VirtualMachinesGeneralizeParams {
	var ()
	return &VirtualMachinesGeneralizeParams{

		Context: ctx,
	}
}

/*VirtualMachinesGeneralizeParams contains all the parameters to send to the API endpoint
for the virtual machines generalize operation typically these are written to a http.Request
*/
type VirtualMachinesGeneralizeParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string
	/*VMName
	  The name of the virtual machine.

	*/
	VMName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithTimeout(timeout time.Duration) *VirtualMachinesGeneralizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithContext(ctx context.Context) *VirtualMachinesGeneralizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithAPIVersion(aPIVersion string) *VirtualMachinesGeneralizeParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithResourceGroupName(resourceGroupName string) *VirtualMachinesGeneralizeParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithSubscriptionID(subscriptionID string) *VirtualMachinesGeneralizeParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WithVMName adds the vMName to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) WithVMName(vMName string) *VirtualMachinesGeneralizeParams {
	o.SetVMName(vMName)
	return o
}

// SetVMName adds the vmName to the virtual machines generalize params
func (o *VirtualMachinesGeneralizeParams) SetVMName(vMName string) {
	o.VMName = vMName
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualMachinesGeneralizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	// path param vmName
	if err := r.SetPathParam("vmName", o.VMName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
