package virtual_network_gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// NewVirtualNetworkGatewaysResetParams creates a new VirtualNetworkGatewaysResetParams object
// with the default values initialized.
func NewVirtualNetworkGatewaysResetParams() *VirtualNetworkGatewaysResetParams {
	var ()
	return &VirtualNetworkGatewaysResetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVirtualNetworkGatewaysResetParamsWithTimeout creates a new VirtualNetworkGatewaysResetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVirtualNetworkGatewaysResetParamsWithTimeout(timeout time.Duration) *VirtualNetworkGatewaysResetParams {
	var ()
	return &VirtualNetworkGatewaysResetParams{

		timeout: timeout,
	}
}

// NewVirtualNetworkGatewaysResetParamsWithContext creates a new VirtualNetworkGatewaysResetParams object
// with the default values initialized, and the ability to set a context for a request
func NewVirtualNetworkGatewaysResetParamsWithContext(ctx context.Context) *VirtualNetworkGatewaysResetParams {
	var ()
	return &VirtualNetworkGatewaysResetParams{

		Context: ctx,
	}
}

/*VirtualNetworkGatewaysResetParams contains all the parameters to send to the API endpoint
for the virtual network gateways reset operation typically these are written to a http.Request
*/
type VirtualNetworkGatewaysResetParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*Parameters
	  Parameters supplied to the Begin Reset Virtual Network Gateway operation through Network resource provider.

	*/
	Parameters *models.VirtualNetworkGateway
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string
	/*VirtualNetworkGatewayName
	  The name of the virtual network gateway.

	*/
	VirtualNetworkGatewayName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithTimeout(timeout time.Duration) *VirtualNetworkGatewaysResetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithContext(ctx context.Context) *VirtualNetworkGatewaysResetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithAPIVersion(aPIVersion string) *VirtualNetworkGatewaysResetParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithParameters adds the parameters to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithParameters(parameters *models.VirtualNetworkGateway) *VirtualNetworkGatewaysResetParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetParameters(parameters *models.VirtualNetworkGateway) {
	o.Parameters = parameters
}

// WithResourceGroupName adds the resourceGroupName to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithResourceGroupName(resourceGroupName string) *VirtualNetworkGatewaysResetParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithSubscriptionID(subscriptionID string) *VirtualNetworkGatewaysResetParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WithVirtualNetworkGatewayName adds the virtualNetworkGatewayName to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) WithVirtualNetworkGatewayName(virtualNetworkGatewayName string) *VirtualNetworkGatewaysResetParams {
	o.SetVirtualNetworkGatewayName(virtualNetworkGatewayName)
	return o
}

// SetVirtualNetworkGatewayName adds the virtualNetworkGatewayName to the virtual network gateways reset params
func (o *VirtualNetworkGatewaysResetParams) SetVirtualNetworkGatewayName(virtualNetworkGatewayName string) {
	o.VirtualNetworkGatewayName = virtualNetworkGatewayName
}

// WriteToRequest writes these params to a swagger request
func (o *VirtualNetworkGatewaysResetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Parameters == nil {
		o.Parameters = new(models.VirtualNetworkGateway)
	}

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	// path param virtualNetworkGatewayName
	if err := r.SetPathParam("virtualNetworkGatewayName", o.VirtualNetworkGatewayName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
