package virtual_network_gateways

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// VirtualNetworkGatewaysCreateOrUpdateReader is a Reader for the VirtualNetworkGatewaysCreateOrUpdate structure.
type VirtualNetworkGatewaysCreateOrUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualNetworkGatewaysCreateOrUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualNetworkGatewaysCreateOrUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewVirtualNetworkGatewaysCreateOrUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualNetworkGatewaysCreateOrUpdateOK creates a VirtualNetworkGatewaysCreateOrUpdateOK with default headers values
func NewVirtualNetworkGatewaysCreateOrUpdateOK() *VirtualNetworkGatewaysCreateOrUpdateOK {
	return &VirtualNetworkGatewaysCreateOrUpdateOK{}
}

/*VirtualNetworkGatewaysCreateOrUpdateOK handles this case with default header values.

VirtualNetworkGatewaysCreateOrUpdateOK virtual network gateways create or update o k
*/
type VirtualNetworkGatewaysCreateOrUpdateOK struct {
	Payload *models.VirtualNetworkGateway
}

func (o *VirtualNetworkGatewaysCreateOrUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworkGateways/{virtualNetworkGatewayName}][%d] virtualNetworkGatewaysCreateOrUpdateOK  %+v", 200, o.Payload)
}

func (o *VirtualNetworkGatewaysCreateOrUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualNetworkGateway)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualNetworkGatewaysCreateOrUpdateCreated creates a VirtualNetworkGatewaysCreateOrUpdateCreated with default headers values
func NewVirtualNetworkGatewaysCreateOrUpdateCreated() *VirtualNetworkGatewaysCreateOrUpdateCreated {
	return &VirtualNetworkGatewaysCreateOrUpdateCreated{}
}

/*VirtualNetworkGatewaysCreateOrUpdateCreated handles this case with default header values.

VirtualNetworkGatewaysCreateOrUpdateCreated virtual network gateways create or update created
*/
type VirtualNetworkGatewaysCreateOrUpdateCreated struct {
	Payload *models.VirtualNetworkGateway
}

func (o *VirtualNetworkGatewaysCreateOrUpdateCreated) Error() string {
	return fmt.Sprintf("[PUT /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworkGateways/{virtualNetworkGatewayName}][%d] virtualNetworkGatewaysCreateOrUpdateCreated  %+v", 201, o.Payload)
}

func (o *VirtualNetworkGatewaysCreateOrUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualNetworkGateway)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
