package virtual_machine_scale_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/compute/models"
)

// VirtualMachineScaleSetsDeleteReader is a Reader for the VirtualMachineScaleSetsDelete structure.
type VirtualMachineScaleSetsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualMachineScaleSetsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualMachineScaleSetsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewVirtualMachineScaleSetsDeleteAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 204:
		result := NewVirtualMachineScaleSetsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualMachineScaleSetsDeleteOK creates a VirtualMachineScaleSetsDeleteOK with default headers values
func NewVirtualMachineScaleSetsDeleteOK() *VirtualMachineScaleSetsDeleteOK {
	return &VirtualMachineScaleSetsDeleteOK{}
}

/*VirtualMachineScaleSetsDeleteOK handles this case with default header values.

OK
*/
type VirtualMachineScaleSetsDeleteOK struct {
	Payload *models.OperationStatusResponse
}

func (o *VirtualMachineScaleSetsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}][%d] virtualMachineScaleSetsDeleteOK  %+v", 200, o.Payload)
}

func (o *VirtualMachineScaleSetsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualMachineScaleSetsDeleteAccepted creates a VirtualMachineScaleSetsDeleteAccepted with default headers values
func NewVirtualMachineScaleSetsDeleteAccepted() *VirtualMachineScaleSetsDeleteAccepted {
	return &VirtualMachineScaleSetsDeleteAccepted{}
}

/*VirtualMachineScaleSetsDeleteAccepted handles this case with default header values.

Accepted
*/
type VirtualMachineScaleSetsDeleteAccepted struct {
}

func (o *VirtualMachineScaleSetsDeleteAccepted) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}][%d] virtualMachineScaleSetsDeleteAccepted ", 202)
}

func (o *VirtualMachineScaleSetsDeleteAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewVirtualMachineScaleSetsDeleteNoContent creates a VirtualMachineScaleSetsDeleteNoContent with default headers values
func NewVirtualMachineScaleSetsDeleteNoContent() *VirtualMachineScaleSetsDeleteNoContent {
	return &VirtualMachineScaleSetsDeleteNoContent{}
}

/*VirtualMachineScaleSetsDeleteNoContent handles this case with default header values.

No Content
*/
type VirtualMachineScaleSetsDeleteNoContent struct {
}

func (o *VirtualMachineScaleSetsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}][%d] virtualMachineScaleSetsDeleteNoContent ", 204)
}

func (o *VirtualMachineScaleSetsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
