package virtual_machine_scale_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/compute/models"
)

// VirtualMachineScaleSetsRestartReader is a Reader for the VirtualMachineScaleSetsRestart structure.
type VirtualMachineScaleSetsRestartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualMachineScaleSetsRestartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualMachineScaleSetsRestartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewVirtualMachineScaleSetsRestartAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualMachineScaleSetsRestartOK creates a VirtualMachineScaleSetsRestartOK with default headers values
func NewVirtualMachineScaleSetsRestartOK() *VirtualMachineScaleSetsRestartOK {
	return &VirtualMachineScaleSetsRestartOK{}
}

/*VirtualMachineScaleSetsRestartOK handles this case with default header values.

OK
*/
type VirtualMachineScaleSetsRestartOK struct {
	Payload *models.OperationStatusResponse
}

func (o *VirtualMachineScaleSetsRestartOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/restart][%d] virtualMachineScaleSetsRestartOK  %+v", 200, o.Payload)
}

func (o *VirtualMachineScaleSetsRestartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVirtualMachineScaleSetsRestartAccepted creates a VirtualMachineScaleSetsRestartAccepted with default headers values
func NewVirtualMachineScaleSetsRestartAccepted() *VirtualMachineScaleSetsRestartAccepted {
	return &VirtualMachineScaleSetsRestartAccepted{}
}

/*VirtualMachineScaleSetsRestartAccepted handles this case with default header values.

Accepted
*/
type VirtualMachineScaleSetsRestartAccepted struct {
}

func (o *VirtualMachineScaleSetsRestartAccepted) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/restart][%d] virtualMachineScaleSetsRestartAccepted ", 202)
}

func (o *VirtualMachineScaleSetsRestartAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
