package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// DhcpOptions DHCPOptions contains an array of DNS servers available to VMs deployed in the virtual networkStandard DHCP option for a subnet overrides VNET DHCP options.
// swagger:model DhcpOptions
type DhcpOptions struct {

	// Gets or sets list of DNS servers IP addresses
	DNSServers []string `json:"dnsServers"`
}

// Validate validates this dhcp options
func (m *DhcpOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDNSServers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DhcpOptions) validateDNSServers(formats strfmt.Registry) error {

	if swag.IsZero(m.DNSServers) { // not required
		return nil
	}

	return nil
}
