package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ExpressRouteServiceProviderBandwidthsOffered Contains Bandwidths offered in ExpressRouteServiceProviders
// swagger:model ExpressRouteServiceProviderBandwidthsOffered
type ExpressRouteServiceProviderBandwidthsOffered struct {

	// Gets the OfferName
	OfferName string `json:"offerName,omitempty"`

	// Gets the ValueInMbps.
	ValueInMbps int32 `json:"valueInMbps,omitempty"`
}

// Validate validates this express route service provider bandwidths offered
func (m *ExpressRouteServiceProviderBandwidthsOffered) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
