package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// UsageName The Usage Names.
// swagger:model UsageName
type UsageName struct {

	// Gets or sets a localized string describing the resource name.
	LocalizedValue string `json:"localizedValue,omitempty"`

	// Gets or sets a string describing the resource name.
	Value string `json:"value,omitempty"`
}

// Validate validates this usage name
func (m *UsageName) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
