package express_route_circuit_authorizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// NewExpressRouteCircuitAuthorizationsCreateOrUpdateParams creates a new ExpressRouteCircuitAuthorizationsCreateOrUpdateParams object
// with the default values initialized.
func NewExpressRouteCircuitAuthorizationsCreateOrUpdateParams() *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	var ()
	return &ExpressRouteCircuitAuthorizationsCreateOrUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExpressRouteCircuitAuthorizationsCreateOrUpdateParamsWithTimeout creates a new ExpressRouteCircuitAuthorizationsCreateOrUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExpressRouteCircuitAuthorizationsCreateOrUpdateParamsWithTimeout(timeout time.Duration) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	var ()
	return &ExpressRouteCircuitAuthorizationsCreateOrUpdateParams{

		timeout: timeout,
	}
}

// NewExpressRouteCircuitAuthorizationsCreateOrUpdateParamsWithContext creates a new ExpressRouteCircuitAuthorizationsCreateOrUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewExpressRouteCircuitAuthorizationsCreateOrUpdateParamsWithContext(ctx context.Context) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	var ()
	return &ExpressRouteCircuitAuthorizationsCreateOrUpdateParams{

		Context: ctx,
	}
}

/*ExpressRouteCircuitAuthorizationsCreateOrUpdateParams contains all the parameters to send to the API endpoint
for the express route circuit authorizations create or update operation typically these are written to a http.Request
*/
type ExpressRouteCircuitAuthorizationsCreateOrUpdateParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*AuthorizationName
	  The name of the authorization.

	*/
	AuthorizationName string
	/*AuthorizationParameters
	  Parameters supplied to the create/update ExpressRouteCircuitAuthorization operation

	*/
	AuthorizationParameters *models.ExpressRouteCircuitAuthorization
	/*CircuitName
	  The name of the express route circuit.

	*/
	CircuitName string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithTimeout(timeout time.Duration) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithContext(ctx context.Context) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithAPIVersion(aPIVersion string) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithAuthorizationName adds the authorizationName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithAuthorizationName(authorizationName string) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetAuthorizationName(authorizationName)
	return o
}

// SetAuthorizationName adds the authorizationName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetAuthorizationName(authorizationName string) {
	o.AuthorizationName = authorizationName
}

// WithAuthorizationParameters adds the authorizationParameters to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithAuthorizationParameters(authorizationParameters *models.ExpressRouteCircuitAuthorization) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetAuthorizationParameters(authorizationParameters)
	return o
}

// SetAuthorizationParameters adds the authorizationParameters to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetAuthorizationParameters(authorizationParameters *models.ExpressRouteCircuitAuthorization) {
	o.AuthorizationParameters = authorizationParameters
}

// WithCircuitName adds the circuitName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithCircuitName(circuitName string) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetCircuitName(circuitName)
	return o
}

// SetCircuitName adds the circuitName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetCircuitName(circuitName string) {
	o.CircuitName = circuitName
}

// WithResourceGroupName adds the resourceGroupName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithResourceGroupName(resourceGroupName string) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WithSubscriptionID(subscriptionID string) *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the express route circuit authorizations create or update params
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *ExpressRouteCircuitAuthorizationsCreateOrUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param authorizationName
	if err := r.SetPathParam("authorizationName", o.AuthorizationName); err != nil {
		return err
	}

	if o.AuthorizationParameters == nil {
		o.AuthorizationParameters = new(models.ExpressRouteCircuitAuthorization)
	}

	if err := r.SetBodyParam(o.AuthorizationParameters); err != nil {
		return err
	}

	// path param circuitName
	if err := r.SetPathParam("circuitName", o.CircuitName); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
