package express_route_circuit_authorizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// ExpressRouteCircuitAuthorizationsGetReader is a Reader for the ExpressRouteCircuitAuthorizationsGet structure.
type ExpressRouteCircuitAuthorizationsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExpressRouteCircuitAuthorizationsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewExpressRouteCircuitAuthorizationsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewExpressRouteCircuitAuthorizationsGetOK creates a ExpressRouteCircuitAuthorizationsGetOK with default headers values
func NewExpressRouteCircuitAuthorizationsGetOK() *ExpressRouteCircuitAuthorizationsGetOK {
	return &ExpressRouteCircuitAuthorizationsGetOK{}
}

/*ExpressRouteCircuitAuthorizationsGetOK handles this case with default header values.

ExpressRouteCircuitAuthorizationsGetOK express route circuit authorizations get o k
*/
type ExpressRouteCircuitAuthorizationsGetOK struct {
	Payload *models.ExpressRouteCircuitAuthorization
}

func (o *ExpressRouteCircuitAuthorizationsGetOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteCircuits/{circuitName}/authorizations/{authorizationName}][%d] expressRouteCircuitAuthorizationsGetOK  %+v", 200, o.Payload)
}

func (o *ExpressRouteCircuitAuthorizationsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExpressRouteCircuitAuthorization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
