package virtual_machine_scale_set_vms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/compute/models"
)

// VirtualMachineScaleSetVmsListReader is a Reader for the VirtualMachineScaleSetVmsList structure.
type VirtualMachineScaleSetVmsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VirtualMachineScaleSetVmsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVirtualMachineScaleSetVmsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVirtualMachineScaleSetVmsListOK creates a VirtualMachineScaleSetVmsListOK with default headers values
func NewVirtualMachineScaleSetVmsListOK() *VirtualMachineScaleSetVmsListOK {
	return &VirtualMachineScaleSetVmsListOK{}
}

/*VirtualMachineScaleSetVmsListOK handles this case with default header values.

OK
*/
type VirtualMachineScaleSetVmsListOK struct {
	Payload *models.VirtualMachineScaleSetVMListResult
}

func (o *VirtualMachineScaleSetVmsListOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{virtualMachineScaleSetName}/virtualMachines][%d] virtualMachineScaleSetVmsListOK  %+v", 200, o.Payload)
}

func (o *VirtualMachineScaleSetVmsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VirtualMachineScaleSetVMListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
