package storage_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/storage/models"
)

// NewStorageAccountsUpdateParams creates a new StorageAccountsUpdateParams object
// with the default values initialized.
func NewStorageAccountsUpdateParams() *StorageAccountsUpdateParams {
	var ()
	return &StorageAccountsUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStorageAccountsUpdateParamsWithTimeout creates a new StorageAccountsUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStorageAccountsUpdateParamsWithTimeout(timeout time.Duration) *StorageAccountsUpdateParams {
	var ()
	return &StorageAccountsUpdateParams{

		timeout: timeout,
	}
}

// NewStorageAccountsUpdateParamsWithContext creates a new StorageAccountsUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewStorageAccountsUpdateParamsWithContext(ctx context.Context) *StorageAccountsUpdateParams {
	var ()
	return &StorageAccountsUpdateParams{

		Context: ctx,
	}
}

// NewStorageAccountsUpdateParamsWithHTTPClient creates a new StorageAccountsUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStorageAccountsUpdateParamsWithHTTPClient(client *http.Client) *StorageAccountsUpdateParams {
	var ()
	return &StorageAccountsUpdateParams{
		HTTPClient: client,
	}
}

/*StorageAccountsUpdateParams contains all the parameters to send to the API endpoint
for the storage accounts update operation typically these are written to a http.Request
*/
type StorageAccountsUpdateParams struct {

	/*AccountName
	  The name of the storage account within the specified resource group. Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.

	*/
	AccountName string
	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*Parameters
	  The parameters to provide for the updated account.

	*/
	Parameters *models.StorageAccountUpdateParameters
	/*ResourceGroupName
	  The name of the resource group within the user's subscription. The name is case insensitive.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithTimeout(timeout time.Duration) *StorageAccountsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithContext(ctx context.Context) *StorageAccountsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithHTTPClient(client *http.Client) *StorageAccountsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountName adds the accountName to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithAccountName(accountName string) *StorageAccountsUpdateParams {
	o.SetAccountName(accountName)
	return o
}

// SetAccountName adds the accountName to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetAccountName(accountName string) {
	o.AccountName = accountName
}

// WithAPIVersion adds the aPIVersion to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithAPIVersion(aPIVersion string) *StorageAccountsUpdateParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithParameters adds the parameters to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithParameters(parameters *models.StorageAccountUpdateParameters) *StorageAccountsUpdateParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetParameters(parameters *models.StorageAccountUpdateParameters) {
	o.Parameters = parameters
}

// WithResourceGroupName adds the resourceGroupName to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithResourceGroupName(resourceGroupName string) *StorageAccountsUpdateParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the storage accounts update params
func (o *StorageAccountsUpdateParams) WithSubscriptionID(subscriptionID string) *StorageAccountsUpdateParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the storage accounts update params
func (o *StorageAccountsUpdateParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *StorageAccountsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountName
	if err := r.SetPathParam("accountName", o.AccountName); err != nil {
		return err
	}

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Parameters == nil {
		o.Parameters = new(models.StorageAccountUpdateParameters)
	}

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
