package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// APIErrorBase Api error base.
// swagger:model ApiErrorBase
type APIErrorBase struct {

	// The error code.
	Code string `json:"code,omitempty"`

	// The error message.
	Message string `json:"message,omitempty"`

	// The target of the particular error.
	Target string `json:"target,omitempty"`
}

// Validate validates this Api error base
func (m *APIErrorBase) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
