package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// DataDiskImage Contains the data disk images information.
// swagger:model DataDiskImage
type DataDiskImage struct {

	// The LUN number for a data disk. This value is used to identify data disk image inside the VMImage and therefore it must be unique for each data disk.
	// Read Only: true
	Lun int32 `json:"lun,omitempty"`
}

// Validate validates this data disk image
func (m *DataDiskImage) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
