package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HardwareProfile Describes a hardware profile.
// swagger:model HardwareProfile
type HardwareProfile struct {

	// The virtual machine size name.
	VMSize string `json:"vmSize,omitempty"`
}

// Validate validates this hardware profile
func (m *HardwareProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVMSize(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var hardwareProfileTypeVMSizePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Basic_A0","Basic_A1","Basic_A2","Basic_A3","Basic_A4","Standard_A0","Standard_A1","Standard_A2","Standard_A3","Standard_A4","Standard_A5","Standard_A6","Standard_A7","Standard_A8","Standard_A9","Standard_A10","Standard_A11","Standard_D1","Standard_D2","Standard_D3","Standard_D4","Standard_D11","Standard_D12","Standard_D13","Standard_D14","Standard_D1_v2","Standard_D2_v2","Standard_D3_v2","Standard_D4_v2","Standard_D5_v2","Standard_D11_v2","Standard_D12_v2","Standard_D13_v2","Standard_D14_v2","Standard_D15_v2","Standard_DS1","Standard_DS2","Standard_DS3","Standard_DS4","Standard_DS11","Standard_DS12","Standard_DS13","Standard_DS14","Standard_DS1_v2","Standard_DS2_v2","Standard_DS3_v2","Standard_DS4_v2","Standard_DS5_v2","Standard_DS11_v2","Standard_DS12_v2","Standard_DS13_v2","Standard_DS14_v2","Standard_DS15_v2","Standard_G1","Standard_G2","Standard_G3","Standard_G4","Standard_G5","Standard_GS1","Standard_GS2","Standard_GS3","Standard_GS4","Standard_GS5"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hardwareProfileTypeVMSizePropEnum = append(hardwareProfileTypeVMSizePropEnum, v)
	}
}

const (
	// HardwareProfileVMSizeBasicA0 captures enum value "Basic_A0"
	HardwareProfileVMSizeBasicA0 string = "Basic_A0"
	// HardwareProfileVMSizeBasicA1 captures enum value "Basic_A1"
	HardwareProfileVMSizeBasicA1 string = "Basic_A1"
	// HardwareProfileVMSizeBasicA2 captures enum value "Basic_A2"
	HardwareProfileVMSizeBasicA2 string = "Basic_A2"
	// HardwareProfileVMSizeBasicA3 captures enum value "Basic_A3"
	HardwareProfileVMSizeBasicA3 string = "Basic_A3"
	// HardwareProfileVMSizeBasicA4 captures enum value "Basic_A4"
	HardwareProfileVMSizeBasicA4 string = "Basic_A4"
	// HardwareProfileVMSizeStandardA0 captures enum value "Standard_A0"
	HardwareProfileVMSizeStandardA0 string = "Standard_A0"
	// HardwareProfileVMSizeStandardA1 captures enum value "Standard_A1"
	HardwareProfileVMSizeStandardA1 string = "Standard_A1"
	// HardwareProfileVMSizeStandardA2 captures enum value "Standard_A2"
	HardwareProfileVMSizeStandardA2 string = "Standard_A2"
	// HardwareProfileVMSizeStandardA3 captures enum value "Standard_A3"
	HardwareProfileVMSizeStandardA3 string = "Standard_A3"
	// HardwareProfileVMSizeStandardA4 captures enum value "Standard_A4"
	HardwareProfileVMSizeStandardA4 string = "Standard_A4"
	// HardwareProfileVMSizeStandardA5 captures enum value "Standard_A5"
	HardwareProfileVMSizeStandardA5 string = "Standard_A5"
	// HardwareProfileVMSizeStandardA6 captures enum value "Standard_A6"
	HardwareProfileVMSizeStandardA6 string = "Standard_A6"
	// HardwareProfileVMSizeStandardA7 captures enum value "Standard_A7"
	HardwareProfileVMSizeStandardA7 string = "Standard_A7"
	// HardwareProfileVMSizeStandardA8 captures enum value "Standard_A8"
	HardwareProfileVMSizeStandardA8 string = "Standard_A8"
	// HardwareProfileVMSizeStandardA9 captures enum value "Standard_A9"
	HardwareProfileVMSizeStandardA9 string = "Standard_A9"
	// HardwareProfileVMSizeStandardA10 captures enum value "Standard_A10"
	HardwareProfileVMSizeStandardA10 string = "Standard_A10"
	// HardwareProfileVMSizeStandardA11 captures enum value "Standard_A11"
	HardwareProfileVMSizeStandardA11 string = "Standard_A11"
	// HardwareProfileVMSizeStandardD1 captures enum value "Standard_D1"
	HardwareProfileVMSizeStandardD1 string = "Standard_D1"
	// HardwareProfileVMSizeStandardD2 captures enum value "Standard_D2"
	HardwareProfileVMSizeStandardD2 string = "Standard_D2"
	// HardwareProfileVMSizeStandardD3 captures enum value "Standard_D3"
	HardwareProfileVMSizeStandardD3 string = "Standard_D3"
	// HardwareProfileVMSizeStandardD4 captures enum value "Standard_D4"
	HardwareProfileVMSizeStandardD4 string = "Standard_D4"
	// HardwareProfileVMSizeStandardD11 captures enum value "Standard_D11"
	HardwareProfileVMSizeStandardD11 string = "Standard_D11"
	// HardwareProfileVMSizeStandardD12 captures enum value "Standard_D12"
	HardwareProfileVMSizeStandardD12 string = "Standard_D12"
	// HardwareProfileVMSizeStandardD13 captures enum value "Standard_D13"
	HardwareProfileVMSizeStandardD13 string = "Standard_D13"
	// HardwareProfileVMSizeStandardD14 captures enum value "Standard_D14"
	HardwareProfileVMSizeStandardD14 string = "Standard_D14"
	// HardwareProfileVMSizeStandardD1V2 captures enum value "Standard_D1_v2"
	HardwareProfileVMSizeStandardD1V2 string = "Standard_D1_v2"
	// HardwareProfileVMSizeStandardD2V2 captures enum value "Standard_D2_v2"
	HardwareProfileVMSizeStandardD2V2 string = "Standard_D2_v2"
	// HardwareProfileVMSizeStandardD3V2 captures enum value "Standard_D3_v2"
	HardwareProfileVMSizeStandardD3V2 string = "Standard_D3_v2"
	// HardwareProfileVMSizeStandardD4V2 captures enum value "Standard_D4_v2"
	HardwareProfileVMSizeStandardD4V2 string = "Standard_D4_v2"
	// HardwareProfileVMSizeStandardD5V2 captures enum value "Standard_D5_v2"
	HardwareProfileVMSizeStandardD5V2 string = "Standard_D5_v2"
	// HardwareProfileVMSizeStandardD11V2 captures enum value "Standard_D11_v2"
	HardwareProfileVMSizeStandardD11V2 string = "Standard_D11_v2"
	// HardwareProfileVMSizeStandardD12V2 captures enum value "Standard_D12_v2"
	HardwareProfileVMSizeStandardD12V2 string = "Standard_D12_v2"
	// HardwareProfileVMSizeStandardD13V2 captures enum value "Standard_D13_v2"
	HardwareProfileVMSizeStandardD13V2 string = "Standard_D13_v2"
	// HardwareProfileVMSizeStandardD14V2 captures enum value "Standard_D14_v2"
	HardwareProfileVMSizeStandardD14V2 string = "Standard_D14_v2"
	// HardwareProfileVMSizeStandardD15V2 captures enum value "Standard_D15_v2"
	HardwareProfileVMSizeStandardD15V2 string = "Standard_D15_v2"
	// HardwareProfileVMSizeStandardDS1 captures enum value "Standard_DS1"
	HardwareProfileVMSizeStandardDS1 string = "Standard_DS1"
	// HardwareProfileVMSizeStandardDS2 captures enum value "Standard_DS2"
	HardwareProfileVMSizeStandardDS2 string = "Standard_DS2"
	// HardwareProfileVMSizeStandardDS3 captures enum value "Standard_DS3"
	HardwareProfileVMSizeStandardDS3 string = "Standard_DS3"
	// HardwareProfileVMSizeStandardDS4 captures enum value "Standard_DS4"
	HardwareProfileVMSizeStandardDS4 string = "Standard_DS4"
	// HardwareProfileVMSizeStandardDS11 captures enum value "Standard_DS11"
	HardwareProfileVMSizeStandardDS11 string = "Standard_DS11"
	// HardwareProfileVMSizeStandardDS12 captures enum value "Standard_DS12"
	HardwareProfileVMSizeStandardDS12 string = "Standard_DS12"
	// HardwareProfileVMSizeStandardDS13 captures enum value "Standard_DS13"
	HardwareProfileVMSizeStandardDS13 string = "Standard_DS13"
	// HardwareProfileVMSizeStandardDS14 captures enum value "Standard_DS14"
	HardwareProfileVMSizeStandardDS14 string = "Standard_DS14"
	// HardwareProfileVMSizeStandardDS1V2 captures enum value "Standard_DS1_v2"
	HardwareProfileVMSizeStandardDS1V2 string = "Standard_DS1_v2"
	// HardwareProfileVMSizeStandardDS2V2 captures enum value "Standard_DS2_v2"
	HardwareProfileVMSizeStandardDS2V2 string = "Standard_DS2_v2"
	// HardwareProfileVMSizeStandardDS3V2 captures enum value "Standard_DS3_v2"
	HardwareProfileVMSizeStandardDS3V2 string = "Standard_DS3_v2"
	// HardwareProfileVMSizeStandardDS4V2 captures enum value "Standard_DS4_v2"
	HardwareProfileVMSizeStandardDS4V2 string = "Standard_DS4_v2"
	// HardwareProfileVMSizeStandardDS5V2 captures enum value "Standard_DS5_v2"
	HardwareProfileVMSizeStandardDS5V2 string = "Standard_DS5_v2"
	// HardwareProfileVMSizeStandardDS11V2 captures enum value "Standard_DS11_v2"
	HardwareProfileVMSizeStandardDS11V2 string = "Standard_DS11_v2"
	// HardwareProfileVMSizeStandardDS12V2 captures enum value "Standard_DS12_v2"
	HardwareProfileVMSizeStandardDS12V2 string = "Standard_DS12_v2"
	// HardwareProfileVMSizeStandardDS13V2 captures enum value "Standard_DS13_v2"
	HardwareProfileVMSizeStandardDS13V2 string = "Standard_DS13_v2"
	// HardwareProfileVMSizeStandardDS14V2 captures enum value "Standard_DS14_v2"
	HardwareProfileVMSizeStandardDS14V2 string = "Standard_DS14_v2"
	// HardwareProfileVMSizeStandardDS15V2 captures enum value "Standard_DS15_v2"
	HardwareProfileVMSizeStandardDS15V2 string = "Standard_DS15_v2"
	// HardwareProfileVMSizeStandardG1 captures enum value "Standard_G1"
	HardwareProfileVMSizeStandardG1 string = "Standard_G1"
	// HardwareProfileVMSizeStandardG2 captures enum value "Standard_G2"
	HardwareProfileVMSizeStandardG2 string = "Standard_G2"
	// HardwareProfileVMSizeStandardG3 captures enum value "Standard_G3"
	HardwareProfileVMSizeStandardG3 string = "Standard_G3"
	// HardwareProfileVMSizeStandardG4 captures enum value "Standard_G4"
	HardwareProfileVMSizeStandardG4 string = "Standard_G4"
	// HardwareProfileVMSizeStandardG5 captures enum value "Standard_G5"
	HardwareProfileVMSizeStandardG5 string = "Standard_G5"
	// HardwareProfileVMSizeStandardGS1 captures enum value "Standard_GS1"
	HardwareProfileVMSizeStandardGS1 string = "Standard_GS1"
	// HardwareProfileVMSizeStandardGS2 captures enum value "Standard_GS2"
	HardwareProfileVMSizeStandardGS2 string = "Standard_GS2"
	// HardwareProfileVMSizeStandardGS3 captures enum value "Standard_GS3"
	HardwareProfileVMSizeStandardGS3 string = "Standard_GS3"
	// HardwareProfileVMSizeStandardGS4 captures enum value "Standard_GS4"
	HardwareProfileVMSizeStandardGS4 string = "Standard_GS4"
	// HardwareProfileVMSizeStandardGS5 captures enum value "Standard_GS5"
	HardwareProfileVMSizeStandardGS5 string = "Standard_GS5"
)

// prop value enum
func (m *HardwareProfile) validateVMSizeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hardwareProfileTypeVMSizePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HardwareProfile) validateVMSize(formats strfmt.Registry) error {

	if swag.IsZero(m.VMSize) { // not required
		return nil
	}

	// value enum
	if err := m.validateVMSizeEnum("vmSize", "body", m.VMSize); err != nil {
		return err
	}

	return nil
}
