package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// InnerError Inner error details.
// swagger:model InnerError
type InnerError struct {

	// The internal error message or exception dump.
	Errordetail string `json:"errordetail,omitempty"`

	// The exception type.
	Exceptiontype string `json:"exceptiontype,omitempty"`
}

// Validate validates this inner error
func (m *InnerError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
