package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// KeyVaultSecretReference Describes a reference to Key Vault Secret
// swagger:model KeyVaultSecretReference
type KeyVaultSecretReference struct {

	// The URL referencing a secret in a Key Vault.
	// Required: true
	SecretURL *string `json:"secretUrl"`

	// The relative URL of the Key Vault containing the secret.
	// Required: true
	SourceVault *SubResource `json:"sourceVault"`
}

// Validate validates this key vault secret reference
func (m *KeyVaultSecretReference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecretURL(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSourceVault(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KeyVaultSecretReference) validateSecretURL(formats strfmt.Registry) error {

	if err := validate.Required("secretUrl", "body", m.SecretURL); err != nil {
		return err
	}

	return nil
}

func (m *KeyVaultSecretReference) validateSourceVault(formats strfmt.Registry) error {

	if err := validate.Required("sourceVault", "body", m.SourceVault); err != nil {
		return err
	}

	if m.SourceVault != nil {

		if err := m.SourceVault.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
