package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// VirtualMachineScaleSetNetworkProfile Describes a virtual machine scale set network profile.
// swagger:model VirtualMachineScaleSetNetworkProfile
type VirtualMachineScaleSetNetworkProfile struct {

	// The list of network configurations.
	NetworkInterfaceConfigurations []*VirtualMachineScaleSetNetworkConfiguration `json:"networkInterfaceConfigurations"`
}

// Validate validates this virtual machine scale set network profile
func (m *VirtualMachineScaleSetNetworkProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetworkInterfaceConfigurations(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualMachineScaleSetNetworkProfile) validateNetworkInterfaceConfigurations(formats strfmt.Registry) error {

	if swag.IsZero(m.NetworkInterfaceConfigurations) { // not required
		return nil
	}

	for i := 0; i < len(m.NetworkInterfaceConfigurations); i++ {

		if swag.IsZero(m.NetworkInterfaceConfigurations[i]) { // not required
			continue
		}

		if m.NetworkInterfaceConfigurations[i] != nil {

			if err := m.NetworkInterfaceConfigurations[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
