package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// VirtualMachineAgentInstanceView The instance view of the VM Agent running on the virtual machine.
// swagger:model VirtualMachineAgentInstanceView
type VirtualMachineAgentInstanceView struct {

	// The virtual machine extension handler instance view.
	ExtensionHandlers []*VirtualMachineExtensionHandlerInstanceView `json:"extensionHandlers"`

	// The resource status information.
	Statuses []*InstanceViewStatus `json:"statuses"`

	// The VM Agent full version.
	VMAgentVersion string `json:"vmAgentVersion,omitempty"`
}

// Validate validates this virtual machine agent instance view
func (m *VirtualMachineAgentInstanceView) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExtensionHandlers(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateStatuses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualMachineAgentInstanceView) validateExtensionHandlers(formats strfmt.Registry) error {

	if swag.IsZero(m.ExtensionHandlers) { // not required
		return nil
	}

	for i := 0; i < len(m.ExtensionHandlers); i++ {

		if swag.IsZero(m.ExtensionHandlers[i]) { // not required
			continue
		}

		if m.ExtensionHandlers[i] != nil {

			if err := m.ExtensionHandlers[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *VirtualMachineAgentInstanceView) validateStatuses(formats strfmt.Registry) error {

	if swag.IsZero(m.Statuses) { // not required
		return nil
	}

	for i := 0; i < len(m.Statuses); i++ {

		if swag.IsZero(m.Statuses[i]) { // not required
			continue
		}

		if m.Statuses[i] != nil {

			if err := m.Statuses[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
