package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// VirtualMachineScaleSetManagedDiskParameters Describes the parameters of a ScaleSet managed disk.
// swagger:model VirtualMachineScaleSetManagedDiskParameters
type VirtualMachineScaleSetManagedDiskParameters struct {

	// The Storage Account type.
	StorageAccountType StorageAccountType `json:"storageAccountType,omitempty"`
}

// Validate validates this virtual machine scale set managed disk parameters
func (m *VirtualMachineScaleSetManagedDiskParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStorageAccountType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualMachineScaleSetManagedDiskParameters) validateStorageAccountType(formats strfmt.Registry) error {

	if swag.IsZero(m.StorageAccountType) { // not required
		return nil
	}

	if err := m.StorageAccountType.Validate(formats); err != nil {
		return err
	}

	return nil
}
