package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// VirtualMachineExtensionInstanceView The instance view of a virtual machine extension.
// swagger:model VirtualMachineExtensionInstanceView
type VirtualMachineExtensionInstanceView struct {

	// The virtual machine extension name.
	Name string `json:"name,omitempty"`

	// The resource status information.
	Statuses []*InstanceViewStatus `json:"statuses"`

	// The resource status information.
	Substatuses []*InstanceViewStatus `json:"substatuses"`

	// The full type of the extension handler which includes both publisher and type.
	Type string `json:"type,omitempty"`

	// The type version of the extension handler.
	TypeHandlerVersion string `json:"typeHandlerVersion,omitempty"`
}

// Validate validates this virtual machine extension instance view
func (m *VirtualMachineExtensionInstanceView) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatuses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSubstatuses(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VirtualMachineExtensionInstanceView) validateStatuses(formats strfmt.Registry) error {

	if swag.IsZero(m.Statuses) { // not required
		return nil
	}

	for i := 0; i < len(m.Statuses); i++ {

		if swag.IsZero(m.Statuses[i]) { // not required
			continue
		}

		if m.Statuses[i] != nil {

			if err := m.Statuses[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *VirtualMachineExtensionInstanceView) validateSubstatuses(formats strfmt.Registry) error {

	if swag.IsZero(m.Substatuses) { // not required
		return nil
	}

	for i := 0; i < len(m.Substatuses); i++ {

		if swag.IsZero(m.Substatuses[i]) { // not required
			continue
		}

		if m.Substatuses[i] != nil {

			if err := m.Substatuses[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
