package application_package

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batchmanagement/models"
)

// ApplicationPackageActivateReader is a Reader for the ApplicationPackageActivate structure.
type ApplicationPackageActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ApplicationPackageActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewApplicationPackageActivateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewApplicationPackageActivateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewApplicationPackageActivateNoContent creates a ApplicationPackageActivateNoContent with default headers values
func NewApplicationPackageActivateNoContent() *ApplicationPackageActivateNoContent {
	return &ApplicationPackageActivateNoContent{}
}

/*ApplicationPackageActivateNoContent handles this case with default header values.

The operation was successful.
*/
type ApplicationPackageActivateNoContent struct {
}

func (o *ApplicationPackageActivateNoContent) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts/{accountName}/applications/{applicationId}/versions/{version}/activate][%d] applicationPackageActivateNoContent ", 204)
}

func (o *ApplicationPackageActivateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewApplicationPackageActivateDefault creates a ApplicationPackageActivateDefault with default headers values
func NewApplicationPackageActivateDefault(code int) *ApplicationPackageActivateDefault {
	return &ApplicationPackageActivateDefault{
		_statusCode: code,
	}
}

/*ApplicationPackageActivateDefault handles this case with default header values.

Error response describing why the operation failed.
*/
type ApplicationPackageActivateDefault struct {
	_statusCode int

	Payload *models.CloudError
}

// Code gets the status code for the application package activate default response
func (o *ApplicationPackageActivateDefault) Code() int {
	return o._statusCode
}

func (o *ApplicationPackageActivateDefault) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts/{accountName}/applications/{applicationId}/versions/{version}/activate][%d] ApplicationPackage_Activate default  %+v", o._statusCode, o.Payload)
}

func (o *ApplicationPackageActivateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
