package network_security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNetworkSecurityGroupsListAllParams creates a new NetworkSecurityGroupsListAllParams object
// with the default values initialized.
func NewNetworkSecurityGroupsListAllParams() *NetworkSecurityGroupsListAllParams {
	var ()
	return &NetworkSecurityGroupsListAllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetworkSecurityGroupsListAllParamsWithTimeout creates a new NetworkSecurityGroupsListAllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetworkSecurityGroupsListAllParamsWithTimeout(timeout time.Duration) *NetworkSecurityGroupsListAllParams {
	var ()
	return &NetworkSecurityGroupsListAllParams{

		timeout: timeout,
	}
}

// NewNetworkSecurityGroupsListAllParamsWithContext creates a new NetworkSecurityGroupsListAllParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetworkSecurityGroupsListAllParamsWithContext(ctx context.Context) *NetworkSecurityGroupsListAllParams {
	var ()
	return &NetworkSecurityGroupsListAllParams{

		Context: ctx,
	}
}

/*NetworkSecurityGroupsListAllParams contains all the parameters to send to the API endpoint
for the network security groups list all operation typically these are written to a http.Request
*/
type NetworkSecurityGroupsListAllParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) WithTimeout(timeout time.Duration) *NetworkSecurityGroupsListAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) WithContext(ctx context.Context) *NetworkSecurityGroupsListAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) WithAPIVersion(aPIVersion string) *NetworkSecurityGroupsListAllParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithSubscriptionID adds the subscriptionID to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) WithSubscriptionID(subscriptionID string) *NetworkSecurityGroupsListAllParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the network security groups list all params
func (o *NetworkSecurityGroupsListAllParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *NetworkSecurityGroupsListAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
