package network_security_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/network/models"
)

// NetworkSecurityGroupsListAllReader is a Reader for the NetworkSecurityGroupsListAll structure.
type NetworkSecurityGroupsListAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetworkSecurityGroupsListAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetworkSecurityGroupsListAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewNetworkSecurityGroupsListAllOK creates a NetworkSecurityGroupsListAllOK with default headers values
func NewNetworkSecurityGroupsListAllOK() *NetworkSecurityGroupsListAllOK {
	return &NetworkSecurityGroupsListAllOK{}
}

/*NetworkSecurityGroupsListAllOK handles this case with default header values.

NetworkSecurityGroupsListAllOK network security groups list all o k
*/
type NetworkSecurityGroupsListAllOK struct {
	Payload *models.NetworkSecurityGroupListResult
}

func (o *NetworkSecurityGroupsListAllOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/providers/Microsoft.Network/networkSecurityGroups][%d] networkSecurityGroupsListAllOK  %+v", 200, o.Payload)
}

func (o *NetworkSecurityGroupsListAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NetworkSecurityGroupListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
