package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// AddApplicationParameters Parameters for an ApplicationOperations.AddApplication request.
// swagger:model AddApplicationParameters
type AddApplicationParameters struct {

	// A value indicating whether packages within the application may be overwritten using the same version string.
	AllowUpdates bool `json:"allowUpdates,omitempty"`

	// The display name for the application.
	DisplayName string `json:"displayName,omitempty"`
}

// Validate validates this add application parameters
func (m *AddApplicationParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
