package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// AutoStorageBaseProperties The properties related to auto storage account.
// swagger:model AutoStorageBaseProperties
type AutoStorageBaseProperties struct {

	// The resource ID of the storage account to be used for auto storage account.
	// Required: true
	StorageAccountID *string `json:"storageAccountId"`
}

// Validate validates this auto storage base properties
func (m *AutoStorageBaseProperties) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStorageAccountID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AutoStorageBaseProperties) validateStorageAccountID(formats strfmt.Registry) error {

	if err := validate.Required("storageAccountId", "body", m.StorageAccountID); err != nil {
		return err
	}

	return nil
}
