package batch_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batchmanagement/models"
)

// BatchAccountListByResourceGroupReader is a Reader for the BatchAccountListByResourceGroup structure.
type BatchAccountListByResourceGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BatchAccountListByResourceGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBatchAccountListByResourceGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewBatchAccountListByResourceGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBatchAccountListByResourceGroupOK creates a BatchAccountListByResourceGroupOK with default headers values
func NewBatchAccountListByResourceGroupOK() *BatchAccountListByResourceGroupOK {
	return &BatchAccountListByResourceGroupOK{}
}

/*BatchAccountListByResourceGroupOK handles this case with default header values.

The operation was successful. The response contains a list of Batch account entities associated with the resource group.
*/
type BatchAccountListByResourceGroupOK struct {
	Payload *models.BatchAccountListResult
}

func (o *BatchAccountListByResourceGroupOK) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts][%d] batchAccountListByResourceGroupOK  %+v", 200, o.Payload)
}

func (o *BatchAccountListByResourceGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BatchAccountListResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBatchAccountListByResourceGroupDefault creates a BatchAccountListByResourceGroupDefault with default headers values
func NewBatchAccountListByResourceGroupDefault(code int) *BatchAccountListByResourceGroupDefault {
	return &BatchAccountListByResourceGroupDefault{
		_statusCode: code,
	}
}

/*BatchAccountListByResourceGroupDefault handles this case with default header values.

Error response describing why the operation failed.
*/
type BatchAccountListByResourceGroupDefault struct {
	_statusCode int

	Payload *models.CloudError
}

// Code gets the status code for the batch account list by resource group default response
func (o *BatchAccountListByResourceGroupDefault) Code() int {
	return o._statusCode
}

func (o *BatchAccountListByResourceGroupDefault) Error() string {
	return fmt.Sprintf("[GET /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts][%d] BatchAccount_ListByResourceGroup default  %+v", o._statusCode, o.Payload)
}

func (o *BatchAccountListByResourceGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
