package batch_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batchmanagement/models"
)

// BatchAccountRegenerateKeyReader is a Reader for the BatchAccountRegenerateKey structure.
type BatchAccountRegenerateKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BatchAccountRegenerateKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBatchAccountRegenerateKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewBatchAccountRegenerateKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBatchAccountRegenerateKeyOK creates a BatchAccountRegenerateKeyOK with default headers values
func NewBatchAccountRegenerateKeyOK() *BatchAccountRegenerateKeyOK {
	return &BatchAccountRegenerateKeyOK{}
}

/*BatchAccountRegenerateKeyOK handles this case with default header values.

The operation was successful. The response contains the keys of the Batch account.
*/
type BatchAccountRegenerateKeyOK struct {
	Payload *models.BatchAccountKeys
}

func (o *BatchAccountRegenerateKeyOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts/{accountName}/regenerateKeys][%d] batchAccountRegenerateKeyOK  %+v", 200, o.Payload)
}

func (o *BatchAccountRegenerateKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BatchAccountKeys)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBatchAccountRegenerateKeyDefault creates a BatchAccountRegenerateKeyDefault with default headers values
func NewBatchAccountRegenerateKeyDefault(code int) *BatchAccountRegenerateKeyDefault {
	return &BatchAccountRegenerateKeyDefault{
		_statusCode: code,
	}
}

/*BatchAccountRegenerateKeyDefault handles this case with default header values.

Error response describing why the operation failed.
*/
type BatchAccountRegenerateKeyDefault struct {
	_statusCode int

	Payload *models.CloudError
}

// Code gets the status code for the batch account regenerate key default response
func (o *BatchAccountRegenerateKeyDefault) Code() int {
	return o._statusCode
}

func (o *BatchAccountRegenerateKeyDefault) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Batch/batchAccounts/{accountName}/regenerateKeys][%d] BatchAccount_RegenerateKey default  %+v", o._statusCode, o.Payload)
}

func (o *BatchAccountRegenerateKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
