package batch_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batchmanagement/models"
)

// NewBatchAccountUpdateParams creates a new BatchAccountUpdateParams object
// with the default values initialized.
func NewBatchAccountUpdateParams() *BatchAccountUpdateParams {
	var ()
	return &BatchAccountUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewBatchAccountUpdateParamsWithTimeout creates a new BatchAccountUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewBatchAccountUpdateParamsWithTimeout(timeout time.Duration) *BatchAccountUpdateParams {
	var ()
	return &BatchAccountUpdateParams{

		timeout: timeout,
	}
}

// NewBatchAccountUpdateParamsWithContext creates a new BatchAccountUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewBatchAccountUpdateParamsWithContext(ctx context.Context) *BatchAccountUpdateParams {
	var ()
	return &BatchAccountUpdateParams{

		Context: ctx,
	}
}

/*BatchAccountUpdateParams contains all the parameters to send to the API endpoint
for the batch account update operation typically these are written to a http.Request
*/
type BatchAccountUpdateParams struct {

	/*AccountName
	  The name of the account.

	*/
	AccountName string
	/*APIVersion
	  The API version to be used with the HTTP request.

	*/
	APIVersion string
	/*Parameters
	  Additional parameters for account update.

	*/
	Parameters *models.BatchAccountUpdateParameters
	/*ResourceGroupName
	  The name of the resource group that contains the Batch account.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  A unique identifier of a Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the batch account update params
func (o *BatchAccountUpdateParams) WithTimeout(timeout time.Duration) *BatchAccountUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the batch account update params
func (o *BatchAccountUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the batch account update params
func (o *BatchAccountUpdateParams) WithContext(ctx context.Context) *BatchAccountUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the batch account update params
func (o *BatchAccountUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAccountName adds the accountName to the batch account update params
func (o *BatchAccountUpdateParams) WithAccountName(accountName string) *BatchAccountUpdateParams {
	o.SetAccountName(accountName)
	return o
}

// SetAccountName adds the accountName to the batch account update params
func (o *BatchAccountUpdateParams) SetAccountName(accountName string) {
	o.AccountName = accountName
}

// WithAPIVersion adds the aPIVersion to the batch account update params
func (o *BatchAccountUpdateParams) WithAPIVersion(aPIVersion string) *BatchAccountUpdateParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the batch account update params
func (o *BatchAccountUpdateParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithParameters adds the parameters to the batch account update params
func (o *BatchAccountUpdateParams) WithParameters(parameters *models.BatchAccountUpdateParameters) *BatchAccountUpdateParams {
	o.SetParameters(parameters)
	return o
}

// SetParameters adds the parameters to the batch account update params
func (o *BatchAccountUpdateParams) SetParameters(parameters *models.BatchAccountUpdateParameters) {
	o.Parameters = parameters
}

// WithResourceGroupName adds the resourceGroupName to the batch account update params
func (o *BatchAccountUpdateParams) WithResourceGroupName(resourceGroupName string) *BatchAccountUpdateParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the batch account update params
func (o *BatchAccountUpdateParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the batch account update params
func (o *BatchAccountUpdateParams) WithSubscriptionID(subscriptionID string) *BatchAccountUpdateParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the batch account update params
func (o *BatchAccountUpdateParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WriteToRequest writes these params to a swagger request
func (o *BatchAccountUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param accountName
	if err := r.SetPathParam("accountName", o.AccountName); err != nil {
		return err
	}

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Parameters == nil {
		o.Parameters = new(models.BatchAccountUpdateParameters)
	}

	if err := r.SetBodyParam(o.Parameters); err != nil {
		return err
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
