package subnets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSubnetsListParams creates a new SubnetsListParams object
// with the default values initialized.
func NewSubnetsListParams() *SubnetsListParams {
	var ()
	return &SubnetsListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSubnetsListParamsWithTimeout creates a new SubnetsListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSubnetsListParamsWithTimeout(timeout time.Duration) *SubnetsListParams {
	var ()
	return &SubnetsListParams{

		timeout: timeout,
	}
}

// NewSubnetsListParamsWithContext creates a new SubnetsListParams object
// with the default values initialized, and the ability to set a context for a request
func NewSubnetsListParamsWithContext(ctx context.Context) *SubnetsListParams {
	var ()
	return &SubnetsListParams{

		Context: ctx,
	}
}

/*SubnetsListParams contains all the parameters to send to the API endpoint
for the subnets list operation typically these are written to a http.Request
*/
type SubnetsListParams struct {

	/*APIVersion
	  Client Api Version.

	*/
	APIVersion string
	/*ResourceGroupName
	  The name of the resource group.

	*/
	ResourceGroupName string
	/*SubscriptionID
	  Gets subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.

	*/
	SubscriptionID string
	/*VirtualNetworkName
	  The name of the virtual network.

	*/
	VirtualNetworkName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the subnets list params
func (o *SubnetsListParams) WithTimeout(timeout time.Duration) *SubnetsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the subnets list params
func (o *SubnetsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the subnets list params
func (o *SubnetsListParams) WithContext(ctx context.Context) *SubnetsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the subnets list params
func (o *SubnetsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the subnets list params
func (o *SubnetsListParams) WithAPIVersion(aPIVersion string) *SubnetsListParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the subnets list params
func (o *SubnetsListParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithResourceGroupName adds the resourceGroupName to the subnets list params
func (o *SubnetsListParams) WithResourceGroupName(resourceGroupName string) *SubnetsListParams {
	o.SetResourceGroupName(resourceGroupName)
	return o
}

// SetResourceGroupName adds the resourceGroupName to the subnets list params
func (o *SubnetsListParams) SetResourceGroupName(resourceGroupName string) {
	o.ResourceGroupName = resourceGroupName
}

// WithSubscriptionID adds the subscriptionID to the subnets list params
func (o *SubnetsListParams) WithSubscriptionID(subscriptionID string) *SubnetsListParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the subnets list params
func (o *SubnetsListParams) SetSubscriptionID(subscriptionID string) {
	o.SubscriptionID = subscriptionID
}

// WithVirtualNetworkName adds the virtualNetworkName to the subnets list params
func (o *SubnetsListParams) WithVirtualNetworkName(virtualNetworkName string) *SubnetsListParams {
	o.SetVirtualNetworkName(virtualNetworkName)
	return o
}

// SetVirtualNetworkName adds the virtualNetworkName to the subnets list params
func (o *SubnetsListParams) SetVirtualNetworkName(virtualNetworkName string) {
	o.VirtualNetworkName = virtualNetworkName
}

// WriteToRequest writes these params to a swagger request
func (o *SubnetsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param resourceGroupName
	if err := r.SetPathParam("resourceGroupName", o.ResourceGroupName); err != nil {
		return err
	}

	// path param subscriptionId
	if err := r.SetPathParam("subscriptionId", o.SubscriptionID); err != nil {
		return err
	}

	// path param virtualNetworkName
	if err := r.SetPathParam("virtualNetworkName", o.VirtualNetworkName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
