package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/jkawamoto/roadie/cloud/azure/batch/models"
)

// NewTaskAddCollectionParams creates a new TaskAddCollectionParams object
// with the default values initialized.
func NewTaskAddCollectionParams() *TaskAddCollectionParams {
	var (
		returnClientRequestIDDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &TaskAddCollectionParams{
		ReturnClientRequestID: &returnClientRequestIDDefault,
		Timeout:               &timeoutDefault,

		requestTimeout: cr.DefaultTimeout,
	}
}

// NewTaskAddCollectionParamsWithTimeout creates a new TaskAddCollectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTaskAddCollectionParamsWithTimeout(timeout time.Duration) *TaskAddCollectionParams {
	var (
		returnClientRequestIDDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &TaskAddCollectionParams{
		ReturnClientRequestID: &returnClientRequestIDDefault,
		Timeout:               &timeoutDefault,

		requestTimeout: timeout,
	}
}

// NewTaskAddCollectionParamsWithContext creates a new TaskAddCollectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewTaskAddCollectionParamsWithContext(ctx context.Context) *TaskAddCollectionParams {
	var (
		returnClientRequestIdDefault = bool(false)
		timeoutDefault               = int32(30)
	)
	return &TaskAddCollectionParams{
		ReturnClientRequestID: &returnClientRequestIdDefault,
		Timeout:               &timeoutDefault,

		Context: ctx,
	}
}

/*TaskAddCollectionParams contains all the parameters to send to the API endpoint
for the task add collection operation typically these are written to a http.Request
*/
type TaskAddCollectionParams struct {

	/*APIVersion
	  Client API Version.

	*/
	APIVersion string
	/*ClientRequestID
	  The caller-generated request identity, in the form of a GUID with no decoration such as curly braces, e.g. 9C4D50EE-2D56-4CD3-8152-34347DC9F2B0.

	*/
	ClientRequestID *string
	/*JobID
	  The ID of the job to which the task collection is to be added.

	*/
	JobID string
	/*OcpDate
	  The time the request was issued. If not specified, this header will be automatically populated with the current system clock time.

	*/
	OcpDate *string
	/*ReturnClientRequestID
	  Whether the server should return the client-request-id in the response.

	*/
	ReturnClientRequestID *bool
	/*TaskCollection
	  The tasks to be added.

	*/
	TaskCollection *models.TaskAddCollectionParameter
	/*Timeout
	  The maximum time that the server can spend processing the request, in seconds. The default is 30 seconds.

	*/
	Timeout *int32

	requestTimeout time.Duration
	Context        context.Context
	HTTPClient     *http.Client
}

// WithRequestTimeout adds the timeout to the task add collection params
func (o *TaskAddCollectionParams) WithRequestTimeout(timeout time.Duration) *TaskAddCollectionParams {
	o.SetRequestTimeout(timeout)
	return o
}

// SetRequestTimeout adds the timeout to the task add collection params
func (o *TaskAddCollectionParams) SetRequestTimeout(timeout time.Duration) {
	o.requestTimeout = timeout
}

// WithContext adds the context to the task add collection params
func (o *TaskAddCollectionParams) WithContext(ctx context.Context) *TaskAddCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the task add collection params
func (o *TaskAddCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAPIVersion adds the aPIVersion to the task add collection params
func (o *TaskAddCollectionParams) WithAPIVersion(aPIVersion string) *TaskAddCollectionParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the task add collection params
func (o *TaskAddCollectionParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithClientRequestID adds the clientRequestID to the task add collection params
func (o *TaskAddCollectionParams) WithClientRequestID(clientRequestID *string) *TaskAddCollectionParams {
	o.SetClientRequestID(clientRequestID)
	return o
}

// SetClientRequestID adds the clientRequestId to the task add collection params
func (o *TaskAddCollectionParams) SetClientRequestID(clientRequestID *string) {
	o.ClientRequestID = clientRequestID
}

// WithJobID adds the jobID to the task add collection params
func (o *TaskAddCollectionParams) WithJobID(jobID string) *TaskAddCollectionParams {
	o.SetJobID(jobID)
	return o
}

// SetJobID adds the jobId to the task add collection params
func (o *TaskAddCollectionParams) SetJobID(jobID string) {
	o.JobID = jobID
}

// WithOcpDate adds the ocpDate to the task add collection params
func (o *TaskAddCollectionParams) WithOcpDate(ocpDate *string) *TaskAddCollectionParams {
	o.SetOcpDate(ocpDate)
	return o
}

// SetOcpDate adds the ocpDate to the task add collection params
func (o *TaskAddCollectionParams) SetOcpDate(ocpDate *string) {
	o.OcpDate = ocpDate
}

// WithReturnClientRequestID adds the returnClientRequestID to the task add collection params
func (o *TaskAddCollectionParams) WithReturnClientRequestID(returnClientRequestID *bool) *TaskAddCollectionParams {
	o.SetReturnClientRequestID(returnClientRequestID)
	return o
}

// SetReturnClientRequestID adds the returnClientRequestId to the task add collection params
func (o *TaskAddCollectionParams) SetReturnClientRequestID(returnClientRequestID *bool) {
	o.ReturnClientRequestID = returnClientRequestID
}

// WithTaskCollection adds the taskCollection to the task add collection params
func (o *TaskAddCollectionParams) WithTaskCollection(taskCollection *models.TaskAddCollectionParameter) *TaskAddCollectionParams {
	o.SetTaskCollection(taskCollection)
	return o
}

// SetTaskCollection adds the taskCollection to the task add collection params
func (o *TaskAddCollectionParams) SetTaskCollection(taskCollection *models.TaskAddCollectionParameter) {
	o.TaskCollection = taskCollection
}

// WithTimeout adds the timeout to the task add collection params
func (o *TaskAddCollectionParams) WithTimeout(timeout *int32) *TaskAddCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the task add collection params
func (o *TaskAddCollectionParams) SetTimeout(timeout *int32) {
	o.Timeout = timeout
}

// WriteToRequest writes these params to a swagger request
func (o *TaskAddCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.requestTimeout)
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.ClientRequestID != nil {

		// header param client-request-id
		if err := r.SetHeaderParam("client-request-id", *o.ClientRequestID); err != nil {
			return err
		}

	}

	// path param jobId
	if err := r.SetPathParam("jobId", o.JobID); err != nil {
		return err
	}

	if o.OcpDate != nil {

		// header param ocp-date
		if err := r.SetHeaderParam("ocp-date", *o.OcpDate); err != nil {
			return err
		}

	}

	if o.ReturnClientRequestID != nil {

		// header param return-client-request-id
		if err := r.SetHeaderParam("return-client-request-id", swag.FormatBool(*o.ReturnClientRequestID)); err != nil {
			return err
		}

	}

	if o.TaskCollection == nil {
		o.TaskCollection = new(models.TaskAddCollectionParameter)
	}

	if err := r.SetBodyParam(o.TaskCollection); err != nil {
		return err
	}

	if o.Timeout != nil {

		// query param timeout
		var qrTimeout int32
		if o.Timeout != nil {
			qrTimeout = *o.Timeout
		}
		qTimeout := swag.FormatInt32(qrTimeout)
		if qTimeout != "" {
			if err := r.SetQueryParam("timeout", qTimeout); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
